### ISSUE TITLE
Doesn't seem to work with the new Dashboard preview

### ISSUE THREAD

**Issue by HintonBR** [Microsoft/vsts-team-calendar#10]
I have the extension enabled, but we also have the new Dashboarding feature enabled and this extension doesn't seem to show up anywhere now (since the new Overview/Home screen has changed).

**Comment by Guadzilah** [comment]
You will have to check with team

**Comment by Guadzilah** [comment]
Under the GPL you cant change code under the law unless you was the software owner its the law

**Comment by willsmythe** [comment]
Sorry for the delay in closing this. This was resolved last year.
