### ISSUE TITLE
Days Off access denied

### ISSUE THREAD

**Issue by leosmachado** [microsoft/vsts-team-calendar#100]
When click in days off link : 
TF400483: You cannot view information for the following iteration: Rgs\Rodocred\2016\Sprint 06. The iteration path might have been deleted, or it might not be selected for your team.

And days off dont appear in calendar , just in de list.

**Comment by willsmythe** [comment]
@dmarcey - days off not appearing in on the calendar seems to be the biggest problem here. Can you look into what it would take to be more resilient to these types of problems?

**Comment by leosmachado** [comment]
The calendar is trying to acess Rgs\Rodocred\2017\Sprint 01 this is the complete path for the iteration capacity , but TFS use just de last tow path for it,  \2017\Sprint 01 Ex: **/_backlogs/capacity**/2017/Sprint%2001

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
