### ISSUE TITLE
create work item out of an event (via versa)

### ISSUE THREAD

**Issue by Prybe** [microsoft/vsts-team-calendar#101]
first of all, I love your extension! Great job!

Would be great to have an Option to create a work item out of an event.
simply select a Work Item Type and hit "create"
then
Start Date -> Created Date
End Date -> Finish Date
....

Or have the option in a work item to create a event.
Start Date = Created Date
End Date = Finish Date

for me this would be a killer feature.
I need the calender view for work items so many times.

**Comment by willsmythe** [comment]
@dmarcey - did we ever add the extensibility points for plugging in custom actions?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
