### ISSUE TITLE
"Team Calendar by Microsoft DevLabs failed to load" Exception when using SSL

### ISSUE THREAD

**Issue by RachelAmbler** [microsoft/vsts-team-calendar#108]
Calendar works fine when using no encrypted traffic. Fails when using HTTPS.

**Comment by davidattw** [comment]
Same thing happened to me...

**Comment by StingyJack** [comment]
Easy enough to work around, but definitely broken

**Comment by MKiCD** [comment]
I see the same situation, seems it's not yet fixed

**Comment by nschonni** [comment]
@MKiCD the protocol-less CDN links are gone now and the bundled libraries packaged with the extension.
https://github.com/Microsoft/vsts-team-calendar/commit/d2e67aa6cfff14fef5c59db9d184b26391ba1506 which was released as 0.5.197

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
