### ISSUE TITLE
Start on a Monday

### ISSUE THREAD

**Issue by Stoffe** [microsoft/vsts-team-calendar#115]
The calendar seems to always start on a Sunday.
I want the calender to start on a Monday, please add a setting for this.

**Comment by weird-dreams** [comment]
Another one - could you add an option for this?

**Comment by ndeeH** [comment]
I tested to switch my regional settings in my ms live account and in Azure DevOps - but the start of week never changed to monday. It seems it is fix coded for US needs.
Hope to support regional settings some day - because there are regions outside US ;-)

**Comment by Stoffe** [comment]
This seems to now be handled by Azure DevOps, on the linked issue, fixed on Dec 15th 2022.

**Comment by ndeeH** [comment]
@Stoffe I did not find a change in the currently active calendar. There are no new options to set the start of weekday.

**Comment by Stoffe** [comment]
> @Stoffe I did not find a change in the currently active calendar. There are no new options to set the start of weekday.

For me, the calendar starts on monday now, and it seems its based on your locality settings, if you follow the links to the closed issues that are linked above, you can see how they have implemented it.
At least it seems to work for me, so I would check your date and location options to see if that makes any difference.

**Comment by ndeeH** [comment]
My locale settings
Windows
![image](https://user-images.githubusercontent.com/11518242/214855027-9c821032-7690-442e-874d-6f7933b0c83f.png)
Azure DevOps (German)
![image](https://user-images.githubusercontent.com/11518242/214854165-21c65991-089b-409b-a491-ac220c5a242f.png)
MS Account (German)
![image](https://user-images.githubusercontent.com/11518242/214854268-cf189d98-2ea1-4c00-9ddd-e82be90d7ba2.png)
Calendar still starts with monday
![image](https://user-images.githubusercontent.com/11518242/214854657-a461b6fb-1394-4b6b-aa2f-7e16d634be41.png)

@Stoffe Which settings are used for the calendar?

**Comment by Stoffe** [comment]
Hmm, to my understanding it should be the ones in Azure DevOps.
For me its working, located in Sweden, so should work, this is my settings...

![screenshot 347](https://user-images.githubusercontent.com/2631458/214860511-3af7f3d2-2abe-4ced-a6f9-ef7ca7372f34.jpg)

![screenshot 348](https://user-images.githubusercontent.com/2631458/214860561-25b8eff0-eaa3-4d34-95af-d8835200da0e.jpg)

I was refering to this issue that was closed:
https://github.com/microsoft/vsts-team-calendar/issues/115

Weird...
