### ISSUE TITLE
Days Off appear in the sidebar but not on the calendar

### ISSUE THREAD

**Issue by craigeddy** [microsoft/vsts-team-calendar#121]
![image](https://cloud.githubusercontent.com/assets/7506643/21986224/9a34aa5a-dbcc-11e6-8662-1021332a55e8.png)

**Comment by Cardatl** [comment]
I am experiencing this issue too, this one has really become an issue within my organization

**Comment by mokyG** [comment]
Same here ! with this error :
Error getting event data.
Event source: Days off
Reason: Error: Could not load event source Days off. Request timed out.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
