### ISSUE TITLE
Recurrence days off, and connection to outlook calendar 

### ISSUE THREAD

**Issue by BarakBenShlush** [microsoft/vsts-team-calendar#124]
Many developers on my team have day off to study at the Academy, I want to enter it as a recurrence days off.
I also want to allow direct input from team members outlook calendar by some attributes/tags because we duplicate any days off in the outlook and the team calendar

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
