### ISSUE TITLE
Calendar counts weekend days off

### ISSUE THREAD

**Issue by michaeldevenney** [microsoft/vsts-team-calendar#132]
Hi, love the calendar!  I noticed something recently when I scheduled time off that spanned a weekend.  The summary pane to the right seems to be counting the Saturdays and Sundays into the total days showing under my name for days off when the time off spans a weekend.  Not a big deal, but it might be if that number of days off was being used anywhere else to calculate available hours, etc...

Thanks again, keep up the great work!

**Comment by richardzaat** [comment]
Agree, would be good if the calendar uses the work days from the team settings

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
