### ISSUE TITLE
Calendar Items exposed thru Rest Api?

### ISSUE THREAD

**Issue by mariotzki** [microsoft/vsts-team-calendar#133]
Hi -

We'd like to build on top of this calendar feature by accessing the calendar entries. Is it possible to extract this thru the rest api? 

Thanks in advance!

**Comment by figueiredorui** [comment]
Hi @mariotzki 
Have you found a way of getting the calendar data through a REST request?
I have found this article but only shows how to get settings data and not documents data.
[https://docs.microsoft.com/en-us/vsts/extend/develop/data-storage#rest-apis](https://docs.microsoft.com/en-us/vsts/extend/develop/data-storage#rest-apis)

Thanks,
Rui

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
