### ISSUE TITLE
Cannot see the EVENTS created in the Calendar

### ISSUE THREAD

**Issue by pameladimailig** [microsoft/vsts-team-calendar#135]
I am able to see the Days-off but the created events it is not showing in my account but there are users who can see the event.

**Comment by dtmnash** [comment]
We are seeing this issue intermittently as well. Someones the created events do not show up, other times they show up fine.

I have noticed that when they do not show up, it appears to try and load them for a while prior to timing or erroring out. 

![capture](https://user-images.githubusercontent.com/1438391/28173946-aa504168-67b5-11e7-9361-cd57c79cf37d.PNG)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
