### ISSUE TITLE
Adding a day off to the non-default team member

### ISSUE THREAD

**Issue by vadimdr** [microsoft/vsts-team-calendar#136]
Unfortunately, I was not able to add a day off for any of the members of non-default teams. 
I have a project with several teams, so only for the default team members I was able to add the day off in the calendar. For all others the dialog appeared empty

![image](https://cloud.githubusercontent.com/assets/1306004/24210066/57045a5e-0efe-11e7-9d78-a35e20f9eded.png)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
