### ISSUE TITLE
Make all resources in the Calendar self-contained in extension

### ISSUE THREAD

**Issue by T-Hugs** [microsoft/vsts-team-calendar#137]
Hi,

My customer has a locked down environment (no access to internet on server or desktops) and they are trying to use the MS DevLabs TeamCalendar extension.

Debugging the code the following error is returned:

TypeError: this._element.fullCalendar is not a fuction.

Looking deeper – a handful of HTTP GETs are failing to pull down from these sites: 
•	Cdnjs.cloudflare.com
•	Maxcdn.bootstrapcnd.com
•	Ajax.googlepais

The resources its attempting pulling down are CSS, JS files.  Looks like fullCalendar function is part of fullCalendar.min.js.

Is it possible to bundle all required resources into this extension so it can be used on-prem in a secure environment?

Regards

**Comment by tancb** [comment]
you can download the master and make some simple changes and build your own package and get it installed. 

key changes are to download the remote javascript and css stylesheet, put them in the folder and update the reference in the HTML files. thereafter follow the instructions in the main git page and build the package. Things get slightly more complicated if it's VSO, as mine was on-premise,  i did not publish.

hopefully the team will get it implemented by default...for now, I guess this is the only workaround. 
Good news is that customized version will still retain existing data.

**Comment by RangerDjanger** [comment]
Thanks for advising @tancb .

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
