### ISSUE TITLE
Everyone as a days off requires an iteration selection

### ISSUE THREAD

**Issue by kevin2l** [microsoft/vsts-team-calendar#140]
While good for planning purposes, it may be a holiday, in which case it should be allowed to be empty simply to record as it may or may not impact velocity.  

It also doesn't show on the calendar if the days off is beyond my current iterations.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
