### ISSUE TITLE
QUESTION: How do I update team cal to latest version?

### ISSUE THREAD

**Issue by corrededos** [Microsoft/vsts-team-calendar#146]
Is it safe to do an uninstall and then install the latest build?
I am scared to loose important calendar data.

Thanks!

**Comment by tancb** [comment]
in TFS manage extension, there's a context menu that you can activate to choose update. 

on-premise, there is a small arrow beside the extension. For VSO, right click brings up the context menu

**Comment by corrededos** [comment]
Excellent, thanks for the information! 
:)

**Comment by corrededos** [comment]
Hi again @tancb, 

I'm onprem, at the local TFSServer as TFSSETUP (admin account) but cannot find that small arrow. I have full blown rights. Can you attach a screen shoot please or tell me if Im at the wrong place looking for that context-menu?
Cheers
/Mike

![image](https://cloud.githubusercontent.com/assets/14276414/25946847/0d2fce6a-364d-11e7-8247-258cd40418ff.png)

**Comment by tancb** [comment]
ok. as i dont have access to the system now, let me try to recall. 
in the main tfs page, top right, click on the mktplace then choose browse. it will bring u to a page where u will notice a card at btm right thst allow you to click manage extension. 

if u go through this way, u probably see a list of extension, listed in a verticsl list. there u will see the mini down arrow beside the extension. 

i hope my memory is correct. if not u will have ro wait till i get back office which is on monday

**Comment by willsmythe** [comment]
In TFS 2015, you just need to download the latest version of the extension from the Marketplace and upload it to your local TFS server. In TFS 2017, assuming your TFS server has connectivity to the internet, extensions acquired via the connected Marketplace experience or manually downloaded and uploaded are automatically updated. See: https://docs.microsoft.com/en-us/vsts/marketplace/get-tfs-extensions#install-extensions-while-connected-to-tfs for more details.
