### ISSUE TITLE
Days off added are not reflecting in capacity

### ISSUE THREAD

**Issue by syedwalihasan** [microsoft/vsts-team-calendar#148]
I added days off for a team member in future iteration from calendar extension, when I checked the capacity for that iteration, days off are not appearing.
Then I added days off from Capacity screen, now calendar is showing both added from Calendar and from capacity.

**Comment by florinangelescu** [comment]
Subscribe. I see no one even cared about looking into it...

**Comment by roberto-orsted** [comment]
subscribe. This issue is still present as of 18-JUL-2019

**Comment by roberto-orsted** [comment]
is there any chance that this will be investigated?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
