### ISSUE TITLE
Team Calendar Disappear

### ISSUE THREAD

**Issue by camimcosta** [microsoft/vsts-team-calendar#149]
Hi,
We are using the TFS since August 2016, till a couple days ago we asked to install the free version of Team Calendar Extention. It was working, very slow, but it was. Today the Calendar disappear. Seams that is no compatibility between the new version TFS 2017 Update 1, performed in March. 

Please you support,
Camila Maia Costa

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
