### ISSUE TITLE
Can't find team member.  Should auto complete or show a drop down list to search

### ISSUE THREAD

**Issue by DennisHsuDevOps** [microsoft/vsts-team-calendar#158]

**Comment by willsmythe** [comment]
Is your team's membership composed of other groups? If so, this is a known issue where groups are not getting expanded and therefore the list of team members doesn't necessarily show all member users.

**Comment by chrisbalt** [comment]
Also having the same issue. Can't figure out any rhyme or reason why this occurring. I've tried adding the "missing" users directly to the project team as to not be a part of an included team or group. Any ideas on how to resolve this issue?

**Comment by CDornbush** [comment]
Our policy is that all AzDO membership is through AD groups.  AzDO won't allow you to add an individual to a team that is already a member of an AD group.  As a result, we enter our days off as events on the calendar which causes additional work for the scrum master.  He needs to look at the calendar and then manually enter the days off on the sprint capacity board.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
