### ISSUE TITLE
my holidays are not showing

### ISSUE THREAD

**Issue by eletu3001** [microsoft/vsts-team-calendar#159]
I click on 'add days off' and select my days off and all yet it doesn't show on the calendar that I have booked any days off

**Comment by willsmythe** [comment]
Are you using the extension on VSTS or TFS (on-prem?)? If TFS, what version?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
