### ISSUE TITLE
Tag releases and use GitHub release page in this repo

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vsts-team-calendar#163]
In order to track what has changed between versions published to the Markeplace, it would help to git tag the releases.
For bonus points, adding the release notes directly to https://github.com/Microsoft/vsts-team-calendar/releases after tagging would be even better

**Comment by willsmythe** [comment]
@nschonni  - good suggestion. I went ahead and tagged the current release (https://github.com/Microsoft/vsts-team-calendar/releases/tag/0.5.6)

@dmarcey - we should do this on the next update. It's a good way for correlating the extension version with the source version and for showing "what's new".

**Comment by nschonni** [comment]
Hey @willsmythe @trevorsg @nkirchem, it looks like the last tag was for 0.5.10, but a few release have been pushed to the gallery in-between since it jumped up to 0.5.94 now

**Comment by trevorsg** [comment]
@willsmythe Can we add this as a step to the build definition?
