### ISSUE TITLE
Unable to view events and days off in calendar

### ISSUE THREAD

**Issue by sumitbhutanirategain** [microsoft/vsts-team-calendar#165]
Hi,

I am unable to view events and days off in calendar even though my access rights are of stakeholder.

Please help me.

Thanks,
Sumit
![bug in tfs](https://user-images.githubusercontent.com/30862780/29116546-bd661b60-7d18-11e7-8be5-8bd0dc2a17ab.jpg)

**Comment by willsmythe** [comment]
Can you press F12 in your browser, refresh the page, and then look at / send any errors that appear in the console or network tabs?

**Comment by SWarnberg** [comment]
I have the same problem with our installation. It seems to have happened after one of the latest TFS updates. We have Update 3 of 2017.
The console shows the following errors:

Current window: jvsoutalm01/tfs/JeevesERP/JeevesPlatform/Kernel%20Feature%20Team/_apps/hub/ms-devlabs.team-calendar.calendar
Error getting event data.
Event source: Event
Reason: Error: Could not load event source Event. Request timed out.
Calendar.js (241,21)
Error getting event data.
Event source: Days off
Reason: Error: Could not load event source Days off. Request timed out.
Calendar.js (241,21)

The Calendar add-in is performing extremely slow after latest updates.

**Comment by ansvcholayi** [comment]
Hi, we are also seeing this error , 
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/123471666/219685859-5496515b-9242-49b2-914e-0753792f2dcf.png)

Failed to set referrer policy: A policy specified by a meta element must contain only one token. The referrer policy has been left unchanged.
main.js:20961 
       Error getting event data.
Event source: Days off
Reason: Could not load event source Days off. Request timed out.
(anonymous) @ main.js:20961


Can you please let us know if you have found a solution for this issue ?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
