### ISSUE TITLE
Data missing after import from TFS to VSTS

### ISSUE THREAD

**Issue by MrHinsh** [microsoft/vsts-team-calendar#166]
Guys, 

We has the plugin installed on TFS and have many teams using it. We just imported out entire collection to VSTS and the data for the plugin is missing.

Can you help?

-MrHinsh

**Comment by MrHinsh** [comment]
That would work...

**Comment by RamprasathSaminathan** [comment]
Hi @willsmythe , is this already in place ? Can we utilize this to move the data ?

**Comment by willsmythe** [comment]
The feature to export calendar data has not been added (that I know of). We are happy to take a contribution from the community if someone is interesting in adding this, however!

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
