### ISSUE TITLE
Nested iterations don't display on the calendar

### ISSUE THREAD

**Issue by jrdodds** [microsoft/vsts-team-calendar#169]
Iterations support a hierarchy of children. However nested iterations do not display on the team calendar. Only top level iterations that have no children are shown on the calendar.

It this a bug or by design?

If by design can support for nested iterations be added?

It is very useful with multiple teams as areas in one team project to use nested iterations to represent different sprint schedules.

Thanks

**Comment by willsmythe** [comment]
@jrdodds - good suggestion. We will take a look.

**Comment by willsmythe** [comment]
@jrdodds - good suggestion. We will take a look.

**Comment by iragl** [comment]
It is 2019 and this is still the behaviour... Any update if this will be supported? @willsmythe 

It would be very useful in a project with multiple teams (area paths) to be able to have a common overview across teams.

**Comment by willsmythe** [comment]
There's no plan to add support for this right now. We are definitely open to contributions from the community, however. :)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
