### ISSUE TITLE
not able to add team day offs from calendar

### ISSUE THREAD

**Issue by Balkiran** [microsoft/vsts-team-calendar#171]

**Comment by willsmythe** [comment]
Are you using the extension on VSTS or TFS (on-prem?)? If TFS, what version?

What happens when you try to add a team off? Do you not get the option? Or does it fail with an error?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
