### ISSUE TITLE
npm run build fails on tsc -p .

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vsts-team-calendar#172]
I'm trying to follow the compile instructions in the readme, but it's failing.  When I run "npm run build", the message says to "tell the author that this fails on your system:   tsc -p ."

-p isn't even a valid switch on my tsc - anyone know what I'm missing?

**Comment by pabrams** [comment]
Okay, I figured out that I had to remove a path variable as described here:   https://stackoverflow.com/questions/15301451/how-to-upgrade-typescript-to-the-latest-version
and now my tsc does have a -p switch, and is reporting its version as 2.5.2 (same as typescript now), but compile is still failing.

Here's what I'm getting:
C:\Temp\tfs-team-calendar\vsts-team-calendar-master>npm run build

> vso-team-calendar@0.0.2 build C:\Temp\tfs-team-calendar\vsts-team-calendar-mas
ter
> npm run compile

npm WARN invalid config loglevel="notice"

> vso-team-calendar@0.0.2 compile C:\Temp\tfs-team-calendar\vsts-team-calendar-m
aster
> tsc -p .

node_modules/@types/react/index.d.ts(165,11): error TS2559: Type 'Component<P, S
>' has no properties in common with type 'ComponentLifecycle<P, S>'.
node_modules/vss-web-extension-sdk/typings/vss.d.ts(3463,14): error TS2559: Type
 'TemplateViewModel' has no properties in common with type 'EnhancementOptions'.

node_modules/vss-web-extension-sdk/typings/vss.d.ts(9965,14): error TS2415: Clas
s 'ComboDateBehavior' incorrectly extends base class 'BaseComboBehavior'.
  Types of property 'getValue' are incompatible.
    Type '() => Date' is not assignable to type '<TValue>() => TValue'.
      Type 'Date' is not assignable to type 'TValue'.
node_modules/vss-web-extension-sdk/typings/vss.d.ts(10050,14): error TS2415: Cla
ss 'ComboMultiValueBehavior' incorrectly extends base class 'ComboListBehavior'.

  Types of property 'getValue' are incompatible.
    Type '() => string[]' is not assignable to type '<TValue>() => TValue'.
      Type 'string[]' is not assignable to type 'TValue'.
node_modules/vss-web-extension-sdk/typings/vss.d.ts(10224,14): error TS2417: Cla
ss static side 'typeof DialogO' incorrectly extends base class static side 'type
of AjaxPanelO'.
  Types of property 'create' are incompatible.
    Type '<T extends Dialog>(dialogType: new (options: any) => T, options?: any)
 => T' is not assignable to type '<TControl extends Control<any>, TOptions>(cont
rolType: new (options: TOptions) => TControl, conta...'.
      Types of parameters 'dialogType' and 'controlType' are incompatible.
        Type 'new (options: TOptions) => TControl' is not assignable to type 'ne
w (options: any) => Dialog'.
          Type 'TControl' is not assignable to type 'Dialog'.
            Type 'Control<any>' is not assignable to type 'Dialog'.
              Property '_specifiedMaxWidth' is missing in type 'Control<any>'.
src/Calendar/Calendar.ts(256,26): error TS2559: Type 'EventObject[]' has no prop
erties in common with type 'EventSource'.
src/Calendar/Calendar.ts(307,30): error TS2559: Type 'any[]' has no properties i
n common with type 'EventSource'.
src/Calendar/Calendar.ts(311,30): error TS2559: Type 'undefined[]' has no proper
ties in common with type 'EventSource'.
src/Calendar/Dialogs.ts(135,67): error TS2345: Argument of type '(fields: IAddEv
entContent[]) => void' is not assignable to parameter of type '(value: IAddEvent
Content) => void'.
  Types of parameters 'fields' and 'value' are incompatible.
    Type 'IAddEventContent' is not assignable to type 'IAddEventContent[]'.
      Property 'length' is missing in type 'IAddEventContent'.
src/Calendar/Dialogs.ts(136,29): error TS2559: Type 'IAddEventContent[]' has no
properties in common with type 'IAddEventContent'.
src/Calendar/EventSources/FreeFormEventsSource.ts(115,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<IEventCategory[]>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: IEventCategory[]) => void | IPromise<U>, onReject?: (reason: any) => voi...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'IEventCategory[]'.
            Property 'length' is missing in type '{}'.
src/Calendar/EventSources/FreeFormEventsSource.ts(135,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<CalendarEvent>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: CalendarEvent) => void | IPromise<U>, onReject?: (reason: any) => void |...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'CalendarEvent'.
            Property 'title' is missing in type '{}'.
src/Calendar/EventSources/FreeFormEventsSource.ts(148,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<IEventCategory>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: IEventCategory) => void | IPromise<U>, onReject?: (reason: any) => void ...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'IEventCategory'.
            Property 'id' is missing in type '{}'.
src/Calendar/EventSources/FreeFormEventsSource.ts(172,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<CalendarEvent[]>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: CalendarEvent[]) => void | IPromise<U>, onReject?: (reason: any) => void...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'CalendarEvent[]'.
            Property 'length' is missing in type '{}'.
src/Calendar/EventSources/FreeFormEventsSource.ts(189,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<IEventCategory[]>'.
src/Calendar/EventSources/FreeFormEventsSource.ts(194,9): error TS2322: Type 'IP
romise<{}>' is not assignable to type 'IPromise<CalendarEvent>'.
  Type '{}' is not assignable to type 'CalendarEvent'.
src/Calendar/EventSources/FreeFormEventsSource.ts(257,9): error TS2322: Type 'Pr
omise<{}>' is not assignable to type 'IPromise<string>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: string) => void | IPromise<U>, onReject?: (reason: any) => void | IPromi...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'string'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(283,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<CalendarEvent>'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(330,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<CalendarEvent[]>'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(377,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<CalendarEvent>'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(397,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<string>'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(406,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<TeamSettingsDaysOff>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: TeamSettingsDaysOff) => void | IPromise<U>, onReject?: (reason: any) => ...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'TeamSettingsDaysOff'.
            Property 'daysOff' is missing in type '{}'.
src/Calendar/EventSources/VSOCapacityEventSource.ts(431,9): error TS2322: Type '
Promise<{}>' is not assignable to type 'IPromise<TeamMemberCapacity>'.
  Types of property 'then' are incompatible.
    Type '<U>(onFulfill?: (value: {}) => IWhenable<U>, onReject?: (error: any) =
> IWhenable<U>, onProgress?...' is not assignable to type '{ <U>(onFulfill: (val
ue: TeamMemberCapacity) => void | IPromise<U>, onReject?: (reason: any) => v...'
.
      Types of parameters 'onFulfill' and 'onFulfill' are incompatible.
        Types of parameters 'value' and 'value' are incompatible.
          Type '{}' is not assignable to type 'TeamMemberCapacity'.
            Property 'activities' is missing in type '{}'.
src/Calendar/EventSources/VSOIterationEventSource.ts(105,9): error TS2322: Type
'Promise<{}>' is not assignable to type 'IPromise<string>'.
src/Calendar/Views.ts(482,54): error TS2559: Type 'CalendarEventSource' has no p
roperties in common with type 'EventSource'.
src/Calendar/Views.ts(558,58): error TS2559: Type 'CalendarEventSource' has no p
roperties in common with type 'EventSource'.
src/Calendar/Views.ts(581,54): error TS2559: Type 'CalendarEventSource' has no p
roperties in common with type 'EventSource'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vso-team-calendar@0.0.2 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vso-team-calendar@0.0.2 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paul.Abrams\AppData\Roaming\npm-cache\_logs\2017-09-12T20_
45_03_500Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vso-team-calendar@0.0.2 build: `npm run compile`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the vso-team-calendar@0.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paul.Abrams\AppData\Roaming\npm-cache\_logs\2017-09-12T20_
45_03_593Z-debug.log

C:\Temp\tfs-team-calendar\vsts-team-calendar-master>

**Comment by pabrams** [comment]
The log file mentioned at the end of the above dump does not exist (there is no folder "npm-cache_logs", although there is one called "npm-cache" at the same path)

**Comment by pabrams** [comment]
nschonni's PR should fix this issue.  In the mean time, workaround is to downgrade manually to typescript 2.3
`npm install --global typescript@2.3.4`
`npm i -D typescript@2.3`

**Comment by trevorsg** [comment]
Should be fixed now.
