### ISSUE TITLE
Unable to get a list of my team members in the drop down list for Team Member

### ISSUE THREAD

**Issue by cyee1** [microsoft/vsts-team-calendar#174]
When I try to add a day off for someone else in my team, I click on the Team Member drop down list and it doesn't show the full list of my team for the Sprint iteration that I had selected.

**Comment by willsmythe** [comment]
Are you using the extension on VSTS or TFS (on-prem)? If TFS, what version?

Also is your team's membership defined by both individual users and other groups?

**Comment by Miriamyesterlina** [comment]
Hi , 
On the calendar when I want to add days off. I do not see everyone in the team when selecting

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
