### ISSUE TITLE
Get the calendar data through a REST request.

### ISSUE THREAD

**Issue by ghost** [microsoft/vsts-team-calendar#175]
Hi,
I'm looking for a way of getting the calendar data through a REST request?

I have found this article but only shows how to get settings data and not documents data.
https://docs.microsoft.com/en-us/vsts/extend/develop/data-storage#rest-apis

Thanks,
Rui

**Comment by Korayem** [comment]
Duplicate of #133

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
