### ISSUE TITLE
team-calendar by ms-devlabs failed to load.

### ISSUE THREAD

**Issue by RainSchue** [microsoft/vsts-team-calendar#178]
TFS Version = TFS 2017.2 OnPremise

With Chrome Version Version 61.0.3163.100 (Offizieller Build) (64-Bit) I got this error.
-> Failed to load script: http://tfsserver:8080/tfs/_static/3rdParty/_scripts/jquery.xdomainrequest.min.js
With IE 11.0.9600 I got a popup the message "Would you shown only secure content".

calendar doesn't work!

![image](https://user-images.githubusercontent.com/11665889/31371591-fab038da-ad91-11e7-9a76-aedac3ebd686.png)

**Comment by nschonni** [comment]
The HTTP endpoint works for my Update 1, but we didn't enforce HTTPS yet

**Comment by madmax0307** [comment]
As you can see we are using http.
The differenz is that we have updated to TFS Update 2.
So i think there is an issue with Update 2.
In our case it works also in the past with Update 1

**Comment by madmax0307** [comment]
Stop!
This weekend we have made a reboot of our TFS-Server.
Now the calender ist working as expected.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
