### ISSUE TITLE
Cross team calendar support?

### ISSUE THREAD

**Issue by Acroo** [microsoft/vsts-team-calendar#185]
Hi!
Within TFS a normal setup is that one project supports several teams with the same project. Normally sprints, events, release and other happenings is cross several teams and if a manager is off that is information that is needed for many teams. 
On the flip side the amount of available people cross team is something that is of interest from a manager perspective. 

So, my request is, is it in the roadmap for team calendar to work across teams. If so when can it be expected? If it is not in the roadmap, any alternative TFS extension would be highly appreciated.

Thanks.
/Christian

**Comment by JRGranell** [comment]
This would be hugely beneficial. We currently have five teams on one project and using the calendar to schedule a cross-team meeting is a no-go. Would be great if we could customise the team sources of a calendar and choose how many calendars we have so that the admin has the flexibility to have a calendar per team, or, if they choose, to roll them all up into a 'project' calendar.

**Comment by doctormetal** [comment]
Here we also have a project with many different teams. Now we need to look at the calendar for each individual team to see the available capacity. It would sure be beneficial to have one calendar to combine the days off for multiple teams at once. This would make it a lot easier to decide which teams has the available capacity to implement which feature.

**Comment by KevinTipps** [comment]
is this see being actively support, as this would be a really useful feature to be able to overview all teams calendar in one view

**Comment by roberto-orsted** [comment]
+1 fir this. Would be very useful for my teams as well

**Comment by jackrbarnes** [comment]
Is this being looked at / done? I too need this feature. 

I have hierarchical areas (with sub areas included) which allows the top level to see all backlog items but you can't seem to do this here because boards are based on teams. Is it that we need hierarchical teams?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
