### ISSUE TITLE
Merge in functionality from Meetings extension by UCL

### ISSUE THREAD

**Issue by pabrams** [microsoft/vsts-team-calendar#188]
This issue is redundant with several other issues, but I want to suggest that a lot of the requested enhancements seem like they are addressed in this "Meetings" extension by UCL: 
https://marketplace.visualstudio.com/items?itemName=UCL.meeting-extension

Unfortunately, I can't get the thing to work, but it looks like functionality from that tool would address at least the following, and more (note that the below list contains duplicates):
#170 #164 #156 #141 #114 #107 #96 #90

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
