### ISSUE TITLE
Ability to link Calendar Events to a delivery plan via markers

### ISSUE THREAD

**Issue by stedelen** [microsoft/vsts-team-calendar#193]
Would there be an ability in the future?

When a user is adding an event in the calendar, if the user has the ability to also create a corresponding marker for the delivery plan as well.  By example, '11/20/2017 Prod Turn Planned'?  This would make key milestones viewable in both places.

Likewise, would the marker on the delivery plan (if ability is added) reference the Event ID from the calendar in the marker title?

Thanks!
Todd

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
