### ISSUE TITLE
Cannot add more than one day off per user in a sprint

### ISSUE THREAD

**Issue by jchauvin-Preventice** [Microsoft/vsts-team-calendar#194]
I'm allowed to add days off for my user profile in my sprint, but when I try to add additional days off in the same sprint, it clears my previous days off. To be clear, I can add days off in the same sprint for multiple people.

Before:
![image](https://user-images.githubusercontent.com/33702702/32860078-1f4165c0-ca16-11e7-9379-6eae56715fde.png)

During the save for new day off in same spring:
![image](https://user-images.githubusercontent.com/33702702/32860086-2a6dc3bc-ca16-11e7-802f-2a53c9fee4d6.png)

After trying to also set the Nov 23 off for Jessica. Notice that it no longer lists Nov 16 as a day off. I did not clear it.
![image](https://user-images.githubusercontent.com/33702702/32860093-32347c8a-ca16-11e7-8030-bf6f8a08de7b.png)

**Comment by stardif0418** [comment]
Same problem here...

**Comment by GingerBr** [comment]
Same here also...TFS On-Prem 2017 Update 2

**Comment by tvanhoeck** [comment]
Same issue (VSTS)
Bug also clears the capacity!
![image](https://user-images.githubusercontent.com/34056614/33309839-d5663ce6-d41f-11e7-85ef-1c4161dfc034.png)

**Comment by trevorsg** [comment]
Fixed in b9b641a. Release to come shortly.

**Comment by jchauvin-Preventice** [comment]
So...I see that the issue I opened has been closed, but in reviewing the fix listed above, it only fixes the capacity and changes the file version.  Am I missing something?  Is there a separate fix for the original problem of allowing a user to have multiple days off?

**Comment by trevorsg** [comment]
@jchauvin-Preventice I am not aware there is still an issue after this fix. I have tested the latest version and I can add multiple days off for any user. If you are still experiencing an issue, can you provide repro steps so I can try it out on my end? Thanks!

**Comment by jchauvin-Preventice** [comment]
Has this been deployed?  If not, the individual steps are outlined in the original open issue that I created Nov 15 (see above).  The capacity item was a comment added Nov 28.  

Just in case you can't see the original issue, the content is pasted below.
-----------------------------------

I'm allowed to add days off for my user profile in my sprint, but when I try to add additional days off in the same sprint, it clears my previous days off. To be clear, I can add days off in the same sprint for multiple people.

Before:
![image](https://user-images.githubusercontent.com/33702702/34272299-5d232878-e655-11e7-8722-3afeac099c51.png)

During the save for new day off in same spring:
![image](https://user-images.githubusercontent.com/33702702/34272291-52ca1a94-e655-11e7-8aaa-89f63bcadb04.png)

After trying to also set the Nov 23 off for Jessica. Notice that it no longer lists Nov 16 as a day off. I did not clear it.
![image](https://user-images.githubusercontent.com/33702702/34272280-490953d0-e655-11e7-8507-7c4cd704c99b.png)

**Comment by trevorsg** [comment]
That is the issue that should be fixed. Yes, the update is deployed.

![image](https://user-images.githubusercontent.com/397836/34272937-55faadb8-e660-11e7-8a04-7df7c91bad66.png)
![image](https://user-images.githubusercontent.com/397836/34272960-6805fc88-e660-11e7-9a79-3104d2c5cf3c.png)
