### ISSUE TITLE
Not loaded correctly

### ISSUE THREAD

**Issue by SMeisam** [microsoft/vsts-team-calendar#200]
Hi
I am using tfs 2017.2 on premises. I can not connect to internet.
I was download the new version of "Team Calender" and install it but I see this error
" _team-calendar by ms-devlabs is taking longer than expected to load. Learn More about this extension, want to get some file from including available support options_."!!!!
what happen? I think that it want to get some file from internet, Do i think right? if yes Why????

**Comment by nikioro** [comment]
I had the same problem. I solved accessing in http. I hope it can help you.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
