### ISSUE TITLE
Failed to Load for one team member but not others

### ISSUE THREAD

**Issue by vhhughes** [microsoft/vsts-team-calendar#201]
We are running TFS 2017 Update 3 and the latest version of Team Calendar (0.5.94). We have one team member for whom the calendar does not come up but presents a "team-calendar by ms-devlabs failed to load. Learn More about this extension, including available support options." That person is using the latest version of Chrome (62.0.3202.94) and had no problems accessing the Team Calendar up until about 3 weeks ago. (don't have the exact date) It is possible the problem may have coincided with the automatic update of the Team Calendar extension on 11/14/2017. In looking at the Console tab of the Chrome F12 tools, we're not seeing anything particularly telling. (screenshot attached) Hoping someone can give us a tip or two on this.

![l_94f0 tmp](https://user-images.githubusercontent.com/8120267/33583368-da341358-d90e-11e7-9412-9d4284b1d74a.PNG)

**Comment by serkan-inci** [comment]
@vhhughes Are you still seeing the issue?

**Comment by RPhay** [comment]
We're seeing this issue as well.  This user has all the right permissions and test users with very limited permissions can see the calendars.  We've tried multiple browsers on this one users box and the result is always the same, no calendar/teams load or are populated in the team dropdown box.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
