### ISSUE TITLE
Cannot see future sprints

### ISSUE THREAD

**Issue by lchanhqo** [Microsoft/vsts-team-calendar#202]
Cannot see future sprints. It keeps defaulting to the current sprint even when I navigate to another month.

**Comment by jrp77nj** [comment]
I am having this same issue.  I'm running TFS Version 15.117.26912.0

**Comment by lchanhqo** [comment]
Also, i've tried Edge, IE 11, Chrome all the same results.

**Comment by nschonni** [comment]
Think this was fixed in https://github.com/Microsoft/vsts-team-calendar/commit/e67044cb64e5d76a52f5fdc6ad5f3d16e84de94e which got published as 0.5.210

**Comment by lchanhqo** [comment]
Thanks! it works!
