### ISSUE TITLE
Current month is shown regardless of selection

### ISSUE THREAD

**Issue by dodiggitydag** [Microsoft/vsts-team-calendar#203]
As of this morning the calendar is no longer working for me.  No matter which month I try, it shows December data.  I'm using the right arrow to change months.  Check out these screen shots.

- [December View](https://www.dropbox.com/s/9dhwn1wxsr1x1fd/VSTS-A-December.png?dl=0)

- [January View](https://www.dropbox.com/s/n02u5vok2kkwfbp/VSTS-B-January%20%28same%20as%20December%29.png?dl=0) (Same as December)

- [February View](https://www.dropbox.com/s/jcdp1bkcoubbrxt/VSTS-C-February%20%28same%20as%20December%29.png?dl=0)  (Same as December)

**Comment by khatibinil** [comment]
I am experiencing the same problem.

**Comment by tpeltone** [comment]
So are we.

**Comment by GingerBr** [comment]
Same issue for us meaning the calendar was useless for our planning session this morning!  Please revert to the previous build asap.

**Comment by eandrewtaylor** [comment]
+1

**Comment by dodiggitydag** [comment]
The issue has been fixed.  It seemed to last only a few days.
