### ISSUE TITLE
Update version from 0.3.18 to 0.5.209 - not working

### ISSUE THREAD

**Issue by VipulChaudhari29** [microsoft/vsts-team-calendar#206]
After update Team Calendar from 0.3.18 to 0.2.219  for our on-primes TFS 2015; Calendar stop working. It doesn’t show days-off and events. Also there is no category dropdown.

**Comment by pabrams** [comment]
Try another browser, or add a polyfill like bluebird

**Comment by VipulChaudhari29** [comment]
I get error on both browser IE 11 and Chrome as per below:
![ie11 error](https://user-images.githubusercontent.com/35807373/35399073-57e920ae-01eb-11e8-9302-6fd9a3d29234.png)

![chrome error](https://user-images.githubusercontent.com/35807373/35399103-6c4f7de0-01eb-11e8-9550-d89ce249c2d8.png)

Can I get VSIX file for version: 0.3.18 calendar from anywhere?

**Comment by pabrams** [comment]
I just cloned, compiled and published the latest commit, and I'm not seeing this on Chrome nor in IE in my vsts account. Some of the dialogs refuse to open in IE, but I think I've just fixed that with #207

**Comment by VipulChaudhari29** [comment]
I am installing Team Calendar On-Premise TFS 2015 Update 3. I cloned, compiled and published the latest commit and It gives me below error.
![team calendar at ie 11](https://user-images.githubusercontent.com/35807373/35518468-95622248-0509-11e8-8309-bc251915befc.png)

**Comment by pabrams** [comment]
@VipulChaudhari29 I believe if you apply my change from #209 it should fix that.
