### ISSUE TITLE
Share calendar across multiple projects

### ISSUE THREAD

**Issue by waheez** [microsoft/vsts-team-calendar#21]
Hi,
How can I share a calendar across multiple projects if its possible. If not may be adding this feature can make this extension very powerful and can be used as team general calendar. Especially for teams working on multiple projects.

**Comment by willsmythe** [comment]
Hey @waheez - can you provide more detail on how you would like this to work? For example, are you asking that "free form" events be visible across multiple teams? Or iterations, days off, etc?

**Comment by waheez** [comment]
Hi @willsmythe Thank you for getting back to me. I will try to elaborate my idea further by showing some screenshots. Basically, I have only one team now that currently working on 3 different projects (3 repos in visual studio) simultaneously. However each project have its own calendar instance. My intention was to use this calendar as a team calendar not project calendar. So I can also record team vacation while recording important events for project lifecycle. 

I have realize that calendar do reflect sprint dates and showing those dates can overlap each other if different project would have different sprint dates. A possible solution would be, if the calendar is marked as shared among two or more projects it may not show sprint dates.

Let me know if that make sense or I need to further shed light on my idea of shared calendar. 
![calendar visual studio team services](https://cloud.githubusercontent.com/assets/515256/13356418/2426088a-dc73-11e5-92a9-cd53d12e96a3.png)

**Comment by waheez** [comment]
Or even better, Add a checkbox on add event dialog to share that particular event among all project's calendar. When you pick time off from add event list  check this checkbox by default otherwise uncheck by default.
![calendar visual studio team services2](https://cloud.githubusercontent.com/assets/515256/13356570/ed219272-dc73-11e5-94d3-fbb19a4f0268.png)

**Comment by jdshkolnik** [comment]
Another way of looking at this might be the ability to create one or more collection-level calendars and decide which team projects are included.

**Comment by sumo300** [comment]
To further enhance this request, what I'd like to have is the option of sharing calendar items from sub-teams up on a parent team's calendar.  We currently have our on-prem configured using the Scaled Agile Framework (SAFe) guidance and have a root portolio team, many sub-program teams, and even more sub-product teams (just hierarchies of areas linked to teams).  It'd be great to share product team calendars either with the program teams or the portfolio team.

https://www.visualstudio.com/en-us/docs/work/scale/scaled-agile-framework
