### ISSUE TITLE
Text color for day off nearly invisible in active iteration

### ISSUE THREAD

**Issue by jcmarling** [microsoft/vsts-team-calendar#210]
The text for days off in the calendar is nearly invisible due to the use of white text on a light background. See attached screenshots.

White background and white text for non-active Sprints
![image](https://user-images.githubusercontent.com/37116419/37045620-604ff002-2134-11e8-9a51-cfb5fb597f52.png)

Light blue background and white text for Active Sprint
![image](https://user-images.githubusercontent.com/37116419/37044229-f214f658-2130-11e8-8e8f-da114261c2ba.png)

**Comment by MTRH** [comment]
I total agree. It would be great if that could be fixed.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
