### ISSUE TITLE
How to setup or choose category in an event?

### ISSUE THREAD

**Issue by anita-zg** [Microsoft/vsts-team-calendar#211]
Hello, how can I set up categories to choose from, when entering a new event? I can't find a place to do that, so I can only choose "Uncategorized".

I am using VS TS.

![image](https://user-images.githubusercontent.com/37209058/37199967-98296ff2-2383-11e8-92e9-feccdd4cc4a5.png)

**Comment by pabrams** [comment]
You just type something, and it will create a new category for you with a random color, if I recollect correctly.

**Comment by anita-zg** [comment]
It works, thanks!

**Comment by shayki5** [comment]
Thanks! I also asked myself how to add categories... maybe you need to make it clear in the release notes..

**Comment by AdzikaN** [comment]
It wasn't easy to find it out :)
