### ISSUE TITLE
Adding days off in Calendar no longer works. OK button stays disabled.

### ISSUE THREAD

**Issue by Jonathan-Ironman** [microsoft/vsts-team-calendar#214]
The OK button stays disabled whatever I choose, even if I change the values in the popup. There is no indication why.

![27441-2018-04-17-09-00-54-calendar-visual-studio-team-se](https://user-images.githubusercontent.com/6589420/38974035-c18d2a06-43a8-11e8-9adb-fb9860e611eb.png)

Triage by MS
"Thank you for your feedback. We have determined that this issue belongs to Calendar extension. You need to be a Team Administrator or above to add "Days Off". If any more other questions, please go to https://github.com/Microsoft/vsts-team-calendar/issues?utm_source=vsmp&utm_medium=ms%20web&utm_campaign=mpdetails to continue tracking the issue. Thank you for helping us build a better Visual Studio."

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
