### ISSUE TITLE
Not able to add new event (day off) to calendar

### ISSUE THREAD

**Issue by Nivki** [microsoft/vsts-team-calendar#216]
TFS2015.3 on Primis. Browser: IE 11
I just install your extension and I was not able to click on day and add event or day off.

**Comment by Nivki** [comment]
disregard - user error. I should read recommendation to use Edge first, before publish this.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
