### ISSUE TITLE
Empty Calendar view with Internet Explorer 11 on Windows 7

### ISSUE THREAD

**Issue by milbrandt** [microsoft/vsts-team-calendar#217]
Windows 7
Internet Explorer 11.0.9600.18977 (no other Browsers allowed by company policy)
TFS Version 15.117.27414.0 "on premise"

Calendar view is empty, only sprint duration is indicated.
- no team availability is indicated
- it's not possible to add off-days
- legend of sprint, days off and events is missing

![2018-05-04 13_42_49-calendar - microsoft team foundation server - internet explorer](https://user-images.githubusercontent.com/26173245/39626289-cd636eb4-4f90-11e8-93fe-c1f3d16e250d.png)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
