### ISSUE TITLE
missing unit tests

### ISSUE THREAD

**Issue by pabrams** [microsoft/vsts-team-calendar#219]
I've spent a lot of time trying to add some unit tests to my fork of this project.  I've tried various tutorials for various packages, but I keep getting crazy errors like 'define is not defined'.  

I've been unable to find any working examples by Microsoft on how to unit test a VSS web extension, at least not one also using Typescript and webpack.

If anyone knows of anyone who's ever successfully unit-tested something like this, a link would be marvellous.

Here's a link to a StackOverflow question I just posted: https://stackoverflow.com/questions/50221726/how-to-run-unit-tests-with-vss-web-extension-sdk-and-typescript-and-webpack

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
