### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by 433MHz** [Microsoft/vsts-team-calendar#22]
Hey there,
I can't install this plugin on our TFS. In MS-Marketplace our TFS is not listed and even if i try to install the zip directly on my TFS under /admin/extension i receive TF400900 (Invalid Zip-Archive).
I also tried to unzip and rezip only the files with subfolders. Still the same error.

(Using TFS2015)
Can anyone help me pls?

Thx!

**Comment by willsmythe** [comment]
Team Calendar uses the new extensions model (introduced at Build 2015). One very nice advantage is that this model supports both TFS in the cloud (VS Team Services) and TFS on-premises. Support for extensions on-prem is available in TFS 2015 Update 2 RC1 (available now). Each TFS instance has its own mini version of the VS Marketplace that supports uploading of extensions. To access this gallery, go to https://myserver:8080/tfs/_gallery
