### ISSUE TITLE
Unable to add days off in calendar view but works to add them in capacity view

### ISSUE THREAD

**Issue by SV25565** [microsoft/vsts-team-calendar#220]
We use AD Group to grant access to our users for VSTS.  Each Team has a general AD group and a Team Admin AD group.  The Team Admin group is then placed under each teams 'Administrators'.  None of the individuals in the Team Admin AD groups can add days off but they do have all the other 'Administrator' roles privileges.

If I place an individual explicitly under a Team's 'Administrators'.  They can add days off.  Due to security concerns we do not want to manage users as individuals in VSTS.  We need AD to be in control.  Please help.  See attached.

![vsts days off issue](https://user-images.githubusercontent.com/36646356/40556442-29a9966a-603c-11e8-9cc1-b10d0c6fbedc.PNG)

**Comment by pundj** [comment]
I'm having same issue.

**Comment by mdanilev** [comment]
I also have this issue.

**Comment by cia0mari** [comment]
same here, all our users are mapped to AD Groups so no chance to add days off at all

**Comment by sksileski** [comment]
We have the same issue as well -it would really help Sprint planning if we could use Days Off

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
