### ISSUE TITLE
TFS 2018 Update 2 Calendar Can't Add Event Again

### ISSUE THREAD

**Issue by MantvydasD** [microsoft/vsts-team-calendar#224]
Hello,

I've seen quite a few versions of this bug reported on vsts-team-calendar. But either they say, they've been resolved, recommeded to use a more administrative user to perform a buggy task, choose anotther browser, bug reported for an older TFS version, or simply not solved by redirecting to some other thread.

However, none of them help. We've got this issue on a brand new version of TFS, that is 2018 Update 2. Bug appears for any modern browser, for any user with the highest privileges.

The issue is, that when going to the monthly calendar view, you right click on a day, you get a context menu prompting you to choose either Add Event or Add days off:

![image](https://user-images.githubusercontent.com/18636437/43520652-17ebc534-959c-11e8-99da-7f45aa0b2308.png)

However, clicking any of these two, doesn't produce anything. Nothing happens. Sometimes the same context menu with two options appears again in the left bottom corner of the browser, but nothing more. 

The issue wasn't there before the upgrade from TFS 2017 Update 1. Only with TFS 2018 Update 2 we have it.

Anyone?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
