### ISSUE TITLE
Cancel button displayed in German under English Locale

### ISSUE THREAD

**Issue by angelwang** [microsoft/vsts-team-calendar#226]
Hi,
We have German team and US team working under the same TFS instance (2018 update2). 
We have latest Team calendar plugin installed. 

Recently we found the Cancel button on Team Calendar shows in German language even under English OS.  See capture attached. 
![8-16-2018 2-56-27 pm](https://user-images.githubusercontent.com/4380905/44239470-4c194880-a16e-11e8-973e-1ce92935724b.png)

Any idea what might be wrong?

Thanks,
Angel

**Comment by br549times3** [comment]
![image](https://user-images.githubusercontent.com/28811413/45042344-190cfb00-b030-11e8-9e3f-53a1d06cea47.png)

**Comment by br549times3** [comment]
I am getting similar.  We have Chinese team members and English.  The buttons are in Chinese.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
