### ISSUE TITLE
Corrupt calendar entries after changing sprint dates (cannot remove/delete)

### ISSUE THREAD

**Issue by stephenacrown** [microsoft/vsts-team-calendar#227]
It appears that we have corrupt calendar entries now after changing sprint dates.

As you can see from the attached, we have a corrupt entry for "Colin" in Sprint 8 (was correct at the time entered), but since we changed sprint dates, the entry does not change to reflect that it is now in Sprint 7.

We've had to add additional entries into Sprint 7 to gain accuracy, and have uninstalled and re-installed the marketplace calendar extension multiple times, but the problem still exists.

**Calendar Extension view:**

![tempsnip](https://user-images.githubusercontent.com/38353501/44393880-b8f55f80-a52d-11e8-90d2-c176a13e49b7.jpg)

![tempsnip1](https://user-images.githubusercontent.com/38353501/44393883-bc88e680-a52d-11e8-97b9-f49a36309c6d.jpg)

As you can see, the correct days are in Sprint 7 (now added via Sprint capacity tab), and Sprint 8 shows 0 days off (which inthe Calendar view shows as Sprint 8):

**Sprint Capacity view:**

![tempsnip2](https://user-images.githubusercontent.com/38353501/44394304-c95a0a00-a52e-11e8-83d6-0b92b2c8afa1.jpg)

![tempsnip3](https://user-images.githubusercontent.com/38353501/44394309-cc54fa80-a52e-11e8-84f6-537282b8abee.jpg)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
