### ISSUE TITLE
Lastest build

### ISSUE THREAD

**Issue by MikulousTheGray** [microsoft/vsts-team-calendar#228]
I took the link from the Microsoft site and installed the version on their site. Comparing the visual with the screenshots, it looks like its a old version. Can someone update the site, or point me to the most up to date code?

**Comment by MikulousTheGray** [comment]
I don't think support really exists for this tool.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
