### ISSUE TITLE
failure to load Team Calendar

### ISSUE THREAD

**Issue by IrU3** [microsoft/vsts-team-calendar#229]
Team Calendar by Microsoft DevLabs failed to load.Learn More about this extension, including available support options.
Failed to load script: http://tfs02:8080/tfs/_static/3rdParty/_scripts/jquery.xdomainrequest.min.js
i just installed the Calendar but get this error when trying to open it.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
