### ISSUE TITLE
Newly defined iterations not accessible/visible in Team Calendar

### ISSUE THREAD

**Issue by tparker62** [microsoft/vsts-team-calendar#230]
We're approaching the completion of our first PI and are getting ready for PI 2 - We have added the PI and supporting sprints, and while they are visible from backlogs, they are not visible in the Team calendar.  Any chance someone knows which step we missed to make them visible?  

Thanks in advance for any wisdom!!

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
