### ISSUE TITLE
Missing icon in the menu

### ISSUE THREAD

**Issue by geordee** [microsoft/vsts-team-calendar#232]
The extension does not have/show an icon on the Azure DevOps menu. Please check the screenshot below.

<img width="241" alt="screen shot 2018-09-29 at 12 42 39 am" src="https://user-images.githubusercontent.com/83303/46232591-af5ae500-c380-11e8-8207-3729a98e8e02.png">

**Comment by ruturaj-h** [comment]
This was fixed in latest update. Let me know if you are still facing the issue.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
