### ISSUE TITLE
Calendar event, Not able to delete

### ISSUE THREAD

**Issue by sharmilade** [microsoft/vsts-team-calendar#233]
Not able to delete event which is cancelled.
Please help

**Comment by ruturaj-h** [comment]
Have you tried right clicking on an event to open context menu and click delete?

**Comment by ruturaj-h** [comment]
If you are on hosted then you can see the new calendar, which has the option to delete on the edit dialog.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
