### ISSUE TITLE
Idea: Copy events/holidays from calendars of other teams

### ISSUE THREAD

**Issue by cycling-jim** [microsoft/vsts-team-calendar#234]
We work in a larger team, made up of sub teams and have to add items to calendars of both teams.

It would be nice to have an easy way to copy from one to another.

**Comment by ljdiamond** [comment]
same idea - would like to copy sprint events from one sprint to another w/out having to retype all of them

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
