### ISSUE TITLE
Days Off not working

### ISSUE THREAD

**Issue by TFSadminacs** [microsoft/vsts-team-calendar#237]
The Azure DevOps Team Calendar isn't allowing us to add days off. We click to add a day off and the pop up opens and says Add Days off but blank. No fields to enter dates or any information. Anyway someone could take a look at this please?
![image](https://user-images.githubusercontent.com/45484968/49283501-e7090a80-f45f-11e8-901f-5607b98c190f.jpg)

I've tried it in Firefox, IE, and Chrome and get the same result. It's very strange behavior because it works on some projects but some it doesn't. Any help with this would be greatly appreciated.

Thanks,

**Comment by CoolDadTx** [comment]
Same here. It was working and then it stopped.

**Comment by TFSadminacs** [comment]
> Same here. It was working and then it stopped.

Yeah, I hope it gets resolved or we get a response from the development team soon. We have a lot of users that use the calendar and no longer able to.

What is strange is that it seems to work in some Azure DevOps project and doesn't work in others.

There is a workaround though.... For any users who have previously entered Time Off, they can go to those and edit the dates on those to future dates. That's a pain but at least an option for now. Thanks for commenting though.. It's great to know others are having the issue.

**Comment by JRTimmerman** [comment]
Same here, not able to manage the working hours now.

**Comment by TFSadminacs** [comment]
> Same here, not able to manage the working hours now.

Thanks for commenting! Hopefully the more users comment, the sooner it will be resolved. It's the time of the year when we use the calendar the most.

**Comment by TFSadminacs** [comment]
The strangest thing happened... For whatever reason, the Days Off functionality is now working again. I'm not sure if anyone else is still having issues so I'll leave this open for now.

**Comment by JRTimmerman** [comment]
working for me now as well.
