### ISSUE TITLE
Days Off Disappeared

### ISSUE THREAD

**Issue by ericmichaelclark** [Microsoft/vsts-team-calendar#241]
We have lost the ability to see days off on the calendar. The option to add them still shows up, but adding days off using it they do not show up on the calendar, nor do they show as days off on the sprint. There is no error indicated when saving. Days off added in the sprint also are no longer showing on the calendar. Screenshots included. 
![capture_1](https://user-images.githubusercontent.com/39193623/53960553-933c3c00-40b4-11e9-8505-a5e0c3634a4d.PNG)
![capture_2](https://user-images.githubusercontent.com/39193623/53960572-99cab380-40b4-11e9-9770-9ceed33c87b0.PNG)

**Comment by dameblue** [comment]
We have this issue also!

**Comment by wesmacdonald** [comment]
We see the following error in the console (Chrome)

Access to XMLHttpRequest at 'https://dev.azure.com/xxxxxxx/_apis/ClientTrace/Events' from origin 'https://ms-devlabs.gallerycdn.vsassets.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Tried both URLs (old & new)

Access to XMLHttpRequest at 'https://xxxxxx.visualstudio.com/_apis/ClientTrace/Events' from origin 'https://ms-devlabs.gallerycdn.vsassets.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by thomkle** [comment]
Having the same issue here as well.

**Comment by jawn** [comment]
Same symptom, different error in console (Chrome). The result is that users get the impression the data is deleted even though that probably is not the case.

workclient.getCapacitities is not a function.

![image](https://user-images.githubusercontent.com/1705112/54021289-11214580-4190-11e9-94eb-7f3c8ddd08bb.png)

**Comment by Pfelix-NL** [comment]
Same issue here. I haven't checked in a while, but I do know it was functioning correctly about 10 days ago at least, as we had dozens of days off over multiple sprints/months. Capacity planning seems to work fine in the sprint capacity screen otherwise.

![image](https://user-images.githubusercontent.com/45064707/54030150-f90aef80-41aa-11e9-84bc-78309c467b93.png)

**Comment by dmarcey** [comment]
Thanks for reporting. We pushed a fix for this issue a few minutes ago, so you should no longer see this issue.

**Comment by jawn** [comment]
Thanks for the quick follow up.

However I'm currently seeing a different error message:

![image](https://user-images.githubusercontent.com/1705112/54033543-e0073c00-41b4-11e9-930b-1b5fae39ef7e.png)

Is this because the fix is still being rolled out?

**Comment by dmarcey** [comment]
Hmmm, that's odd, that URL:
https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.225/1552053146279/lib/jquery/jquery.min.js

does not 404 for me. 

It may be a CDN issue - can you try hitting that URL manually?

**Comment by jawn** [comment]
<Error>
<Code>ResourceNotFound</Code>
<Message>
The specified resource does not exist. RequestId:c35c20d4-101e-00e0-10bb-d5c813000000 Time:2019-03-08T14:32:15.5453064Z
</Message>
</Error>

**Comment by dmarcey** [comment]
@jawn, I just published a new version of the extension to update the version number and get the content re-published to the CDN...can you please try again to use the extension and/or hit this URL:

https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/0.5.226/1552056548939/lib/jquery/jquery.min.js

**Comment by jawn** [comment]
Thanks, it works now!

**Comment by nschonni** [comment]
Pinning the API v5, will drop support for TFS below 2019

**Comment by dmarcey** [comment]
Yep, I actually published an update a few hours later that moved to the 2.1 version of the client so that earlier on-premises servers would not be broken. I just pushed the changes to the repo.
