### ISSUE TITLE
Today's Update - Days off disappeared and cannot create new days off

### ISSUE THREAD

**Issue by TexGoose** [Microsoft/vsts-team-calendar#242]
With today's update, my team's days have disappeared from the calendar. In addition, when I click "Add days off" on the calendar the "Add day off" box appears but the date boxes and sprint boxes are gone. The "OK" button is grayed out and "Cancel" button available to click. I see there was an update pushed to this extension at 10am CST. That is when these issues started,

![1](https://user-images.githubusercontent.com/34754964/54047051-a0802600-419b-11e9-8636-c132674f0bb0.PNG)

**Comment by dmarcey** [comment]
Are you using on-premises TFS or Azure Dev Ops?

**Comment by TexGoose** [comment]
We are using on premise.

**Comment by dmarcey** [comment]
Which version of TFS? I'm working on a fix, but just want to confirm it.

**Comment by TexGoose** [comment]
Here is our version number. Is this what you needed?

Microsoft Visual Studio Team Foundation Server
Version 15.117.27024.0

**Comment by dmarcey** [comment]
Thanks. The fix that I made this morning could have broken some TFS on-premises versions.
I just pushed a new fix that should be compatible with Azure Dev Ops as well as all TFS on-premises versions that supported extensions.

Can you please try again and see if the issue is resolved?

**Comment by dmarcey** [comment]
Actually, we only sync updates for the extensions on a daily basis, so it will take up to 24 hours for the fix to propagate to your server.

I apologize for the disruption.

**Comment by TexGoose** [comment]
No problem at all Derrick. We love the extension and appreciate all the hard work you've done.

**Comment by dmarcey** [comment]
I think this should now be fixed.
@TexGoose please re-open if you're still seeing this issue.
