### ISSUE TITLE
Error on Version 18 on Premises

### ISSUE THREAD

**Issue by akselsoft** [microsoft/vsts-team-calendar#244]
When running on premises and trying to add an event, we are seeing
Line: 424
Error: Object doesn't support property or method 'getTeamMembers'

This was an "out of the box" installation but we've noticed other extensions don't appear to work either.

**Comment by pabrams** [comment]
your tfs probably doesn't have that api.  very difficult for extension devs to support older tfs

**Comment by akselsoft** [comment]
That would be strange on a new 2018 On-premises TFS - wouldn’t it ?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
