### ISSUE TITLE
Remember last selected team

### ISSUE THREAD

**Issue by schmitzel76** [microsoft/vsts-team-calendar#245]
We have a project with multiple teams and when opening the calendar it always selects the first team in the project. This causes users to sometimes enter their days off on the wrong team. As most of the users are a member of one single team, it would make sense to remember the last team a user has selected and use that whenever the calendar is opened again.

**Comment by ruturaj-h** [comment]
If you are on the hosted, that feature has been added in to newest available version of Team calendar.

**Comment by schmitzel76** [comment]
Just tested it and can confirm that the team is now remembered
