### ISSUE TITLE
Issues with Holidays showing in the week-ends as well

### ISSUE THREAD

**Issue by peacharea** [microsoft/vsts-team-calendar#248]
Hello,

We are work in Sprints and I add the Capacity of the team using the existing Capacity option in vsts. 
I also add everyone's Holidays in there and they are automatically shown in this Calendar tool, which is a nice addition for the Product Owners.
However, if someone has a Holiday extending to the next week, it also shows them having Holidays in the week-end, although we do not work on week-ends.
When we created the Sprints we added only Monday to Friday as working days.
I can still find a workaround this by adding the Holiday in two parts, excluding the week-end, but it would be nice if it were easier. 
Is there any other way to do this?

**Comment by ruturaj-h** [comment]
Though the days off show in weekends, the capacity is not affected by it. Ex If you add days off on weekends only then navigate to sprint capacity page then it will show days off to be zero for that particular person.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
