### ISSUE TITLE
Iterations and colors

### ISSUE THREAD

**Issue by JulieGib** [microsoft/vsts-team-calendar#249]
How can I assign a color to different iterations on my calendar. It is hard to read right now and I cannot figure out how to change it. 
![2019-08-29_16h05_08](https://user-images.githubusercontent.com/54688212/63976522-21e3b180-ca77-11e9-9baa-b312716e69cb.png)

**Comment by ruturaj-h** [comment]
The colors are auto assigned, if you are on prem version then current sprint shows in blue and others in white. The newer version on hosted uses blue color for current sprint and 3 different colors for other sprints. Overlapping sprints will show mix of both colors like in your case.

**Comment by MTRH** [comment]
It could be great if this was fixed.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
