### ISSUE TITLE
Would be great to add the features listed below:

### ISSUE THREAD

**Issue by alexanderbrooks** [microsoft/vsts-team-calendar#251]
1. Sync calendar across multiple project within the same Org
2. Manage calendar withing outlook
3. Create reoccurring work items e.g. scrum ceremonies
4. Change the color of each cal item

**Comment by MOlausson** [comment]
@alexanderbrooks great summary. We're closing old issues so we can get back to actively maintaining the extension but will triage and create new issues for enhancements. Feel free to reopen this issue or open new.
