### ISSUE TITLE
Version 2.0.3 deleted history

### ISSUE THREAD

**Issue by dmalchikov** [microsoft/vsts-team-calendar#261]
15 oct 2019 Team Calendar updated to 2.0.2 and 2.0.3
Now we lost all calendar events from the beginning

**Comment by ruturaj-h** [comment]
Are you on onprem version or hosted?

**Comment by dmalchikov** [comment]
hosted.

**Comment by ruturaj-h** [comment]
Also make sure you selected right team as well. The new calendar will select first team in list, once you switch to new team, it will get saved in settings.

**Comment by austinrh322** [comment]
We too have verified this is an issue.  All days off for team members have been removed with the latest version.  We're having our teams re-input as a result.

**Comment by ruturaj-h** [comment]
Hello Austin,

The days off should not have been affected by the update. Please ensure that you have selected the right team and there are no error if you inspect the web page (right click on page, click inspect, in white console window there should not be any errors).

**Comment by ruturaj-h** [comment]
@dmalchikov Please get back to me on ruturajh@microsoft.com with your organization name, I will try to debug the issue from our end.

**Comment by austinrh322** [comment]
No errors in the console.  But all team members that had days off for multiple teams have been removed.  We've looked across all projects.

**Comment by ruturaj-h** [comment]
If the sprint doesn't have start and end date then data (days off) for that iteration wasn't getting fetched by new calendar. I just published a fix for it Version 2.0.9. Let me know if that fixed your issue.

**Comment by austinrh322** [comment]
I just cleared cache and restarted the browser.  No noticeable difference.  Also noticed no messages in the console either.  We have iterations defined with start and end dates, and they appear color coded.  Everything is appearing but no team members are showing with days off like they had yesterday and prior.

**Comment by ruturaj-h** [comment]
@austinrh322 Can you please email me with your organization name on ruturajh@microsoft.com ?
