### ISSUE TITLE
No events displayed for month when events have no defined category (v2.0.9)

### ISSUE THREAD

**Issue by lplavoie** [microsoft/vsts-team-calendar#263]
With the updates today (2.0.9 at this time), events for October no longer load. All other months load fine. 
Console shows this error every time we come back on October:

Color.ts:20 Uncaught (in promise) TypeError: Cannot read property 'slice' of undefined
    at Object.t.generateColor (Color.ts:20)
    at FreeFormEventSource.ts:69
    at Array.forEach (<anonymous>)
    at FreeFormEventSource.ts:53

This month has events where the category = undefined (don't ask me why :P)

**Comment by ruturaj-h** [comment]
@lplavoie I just published a version 2.0.10, let me know if that fixed the issue for you.

**Comment by lplavoie** [comment]
It works! Thank you!
