### ISSUE TITLE
[V 2.0.9] Date picker does not support personal date preferences

### ISSUE THREAD

**Issue by Ste-Re** [microsoft/vsts-team-calendar#264]
With version 2.0.x a new option to define dates in dialog "Add days off" has been added. The feature itself is great, but unfortunately it does not reflect personal date settings. 
I'm not sure if there is a default format used or if language setting from personal profile is used, but for sure not date format setting.

Dialog with US date format:
![image](https://user-images.githubusercontent.com/30718732/67004286-44419500-f0e0-11e9-8090-28c4fd4c4136.png)

My personal settings in "European style"
![image](https://user-images.githubusercontent.com/30718732/67004325-56bbce80-f0e0-11e9-9ec3-97595465374a.png)

**Comment by ruturaj-h** [comment]
The date input uses setting from your machine. If on windows PC, go to Settings, Region, Regional format and choose a desired format that has the date in required format.

**Comment by Ste-Re** [comment]
hmm, I don't think so. Settings at my local machine are same as in DevOps profile. 
![image](https://user-images.githubusercontent.com/30718732/67069039-16aa2980-f17c-11e9-9f53-69365483566e.png)

Using Win 10 + Chrome

But... intersting, when I switch to Edge dates are shown as expected. I'll check Chrome settings if there is an option similar to prefered languag.

**Comment by Ste-Re** [comment]
Did a little research on internet. Look like Chrome is not using local settings in general.
