### ISSUE TITLE
Calendar URL no longer works

### ISSUE THREAD

**Issue by sandyarmstrong** [microsoft/vsts-team-calendar#268]
Our team calendar URL used to be at /_apps/hub/ms-devlabs.team-calendar.calendar?team=guid but today it changed and now it's at /_apps/hub/ms-devlabs.team-calendar.team-calendar?team=guid

Can you please fix everyone's bookmarks and make the old URL continue to work? Thanks!

(copied from https://developercommunity.visualstudio.com/content/problem/782340/calendar-url-no-longer-works.html)

**Comment by ruturaj-h** [comment]
It won't be possible to make older link work for new calendar currently.

To keep the compatibility of previous versions of onprem TFS, both (1.x.x and 2.x.x) versions' files are installed. For everyone on hosted the new version is shown and for everyone on onprem the older version is shown.
