### ISSUE TITLE
Cannot add days off that cross sprint boundaries

### ISSUE THREAD

**Issue by Mystere** [microsoft/vsts-team-calendar#271]
When trying to add days off by right clicking on the calendar, and adding a date range that crosses a sprint boundary, it says "Selected dates are not part of any or same Iteration".  We should be able to add a range of dates and not worry about whether it crosses sprint boundaries or not.

**Comment by ruturaj-h** [comment]
The functionality follows what sprint capacity page does, you can add days off for currently selected sprint. There was a bug in previous where you can add days off to any sprints data, this is version selects a sprint and restrict date range to it. I will look in to adding days off to more than one sprint.

**Comment by Mystere** [comment]
@ruturaj-h  Yes, automatically spanning sprints would be great.  Thanks.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
