### ISSUE TITLE
Calendar display in IE after the new release is different

### ISSUE THREAD

**Issue by Kalaiyappan** [microsoft/vsts-team-calendar#272]
Hello,

I believe the recent release of calendar was on last 18th, The users in our organization had calendar apps working until last Friday perfectly in IE and post which it seems to be messed up. We had tried with compatibility settings with no help

As a work around we have them to use google Chrome where it works, still many of them have difficulties as they have been used to IE. Is there a solution for this ?

**Comment by ruturaj-h** [comment]
Thank you. I was able to reproduce and fix the issue. Publishing the fix soon.

**Comment by ruturaj-h** [comment]
https://github.com/microsoft/vsts-team-calendar/pull/273
