### ISSUE TITLE
Date (-1) being used when entering an item into Azure Devops Calendar

### ISSUE THREAD

**Issue by ashu16815** [microsoft/vsts-team-calendar#274]
When you go to add an entry into the ADO calendar, it puts it in on the day before you select. i.e. Date (-1)

![image1](https://user-images.githubusercontent.com/25782668/67629862-1f200400-f8e2-11e9-84df-8719949d0908.png)

As you can see, it actually adds it to the 18th Feb.
![image2](https://user-images.githubusercontent.com/25782668/67629863-1fb89a80-f8e2-11e9-8681-67f828cfb0d8.png)

Correcting it is easy.
![image3](https://user-images.githubusercontent.com/25782668/67629864-1fb89a80-f8e2-11e9-8749-3c2b2f40dc76.png)

Be good to get this fixed 😊

I can confirm it is consistent in FF, Chrome and Edge.

**Comment by ruturaj-h** [comment]
Hi, Thank you for detailed post about the issue. I tried to reproduce it, I couldn't. What timezone are you in?

**Comment by ruturaj-h** [comment]
Never mind I was able to reproduce it using different time zone. I will update when I find and fix the issue.

**Comment by ruturaj-h** [comment]
I published a fix, let me know if it didn't fix the issue for you.
