### ISSUE TITLE
Cannot find my team's calendar via search

### ISSUE THREAD

**Issue by KimPlausible** [microsoft/vsts-team-calendar#276]
While other teams in our group show up fine, I cannot find my team (SR-DH-SAWHRE-Role Services) while searching from the main calendar.
![image](https://user-images.githubusercontent.com/12721313/67993668-1e97ae00-fbff-11e9-8929-665887cfb2e4.png)

It looks like the get teams API accepts a $top query string, but caps this at 1000 and requires you to make multiple calls using $skip to get the full set of teams when there are more than 1000. 

 The calendar extension needs to be updated to handle this case and make multiple calls.

**Comment by ruturaj-h** [comment]
Thank you for reaching out and investigating the issue. I have published a new version with fix. Let me know if that fixed the issue for you.
