### ISSUE TITLE
Calendar starting on Sunday

### ISSUE THREAD

**Issue by taixes** [microsoft/vsts-team-calendar#278]
Hi,

In all over the world but in the US, weeks start on Monday, not Sunday. However, there is no option (or it's not easily found) to change Azure DevOps' calendar to follow this international rule.

It's quite strange because a couple of weeks ago, before the last calendar's update, it was working ok (actually, with the last version it started on Sunday if you had US English as a preference language and it started on Monday if you had German as your language. I think there should be somewhere the option to change the starting day independently of your language, but I didn't find it...).

![image](https://user-images.githubusercontent.com/20537762/68215296-44e29280-ffdf-11e9-91bf-d4f1a05f3bfb.png)

**Comment by ruturaj-h** [comment]
Locale Data is used to determine the first day of the week. In previous 2.x versions default first day was monday irrespective of locale. If it's not working as expected then please check if your chrome and windows locale setting match.

**Comment by taixes** [comment]
My Windows settings language is English UK. My Chrome language is English (plain, no region specified). I modified it to English UK and the problem was solved. However, I think it would be interesting to be able to configure it independently of the OS/Browser. I might work in a company where I can't modify the software installed (I might share the computer and hence the browser with some colleagues) but I want my DevOps account calendar to be shown staring on Monday/Sunday. Anyways, my problem was solved. Thanks!

**Comment by ruturaj-h** [comment]
Glad to hear that your problem was resolvbed. Previously there used to be locale setting per user in Azure devops account. We no longer do that and support browser and windows setting instead.

**Comment by oliveratgithub** [comment]
> I modified it to English UK and the problem was solved.
Awesome - was looking for that! Had exactly the same problem. Thanks a lot!

> However, I think it would be interesting to be able to configure it independently of the OS/Browser. I might work in a company where I can't modify the software installed (I might share the computer and hence the browser with some colleagues) but I want my DevOps account calendar to be shown staring on Monday/Sunday. Anyways, my problem was solved. Thanks!
Fully agree! Was looking 15 minutes for where you can configure the Calendar in Azure DevOps to start on "Monday" for everybody in my Team... Didn't know I was probably the only one suffering from the Starts-on-Monday-issue...
