### ISSUE TITLE
Cannot select at Team at top of calendar screen so no Calendar shown

### ISSUE THREAD

**Issue by tuckmeat** [microsoft/vsts-team-calendar#281]
This just started  happening:  Select the calendar menu item and no calendar comes up. Noticed the new selection dropdown at top of screen, so click that to select at team and the dropdown is blank.  We have MANY teams defined within the project.

**Comment by ruturaj-h** [comment]
Seems like there was error fetching teams, can you please get the error from console? In order to do that, right click on the page, go to inspect component, click on console and refresh the page.

**Comment by tuckmeat** [comment]
Shortly after I posted this, I inspected the error messages on the console and saw that there was some type of javascript (if I remember correctly?) library that was missing.  I uninstalled the calendar and reinstalled and everything was fine again.  So I think this broke because of some problem during an upgrade.

**Comment by ruturaj-h** [comment]
Might be related to cache. Glad it worked out for you.
