### ISSUE TITLE
Question - is there any way to have hyperlinks supported in the Description field?

### ISSUE THREAD

**Issue by peterhamilton-cpx** [microsoft/vsts-team-calendar#282]
Hi all,
 
Is there any way to have clickable hyperlinks in the Description field for a Calendar item?  They don't work with a simple link, nor with a full anchor tag:

![image](https://user-images.githubusercontent.com/58074761/69424068-ae5be400-0cf5-11ea-8908-459364e06d87.png)

Thank you...

**Comment by ruturaj-h** [comment]
Since the input type in plain text for description and only place we show it is in text field in edit dialog, I don't think it is feasible to have links.
