### ISSUE TITLE
After Update to AzureDevOps2019_1.1 (premises) days off are not any more shown up in the calendar

### ISSUE THREAD

**Issue by Checker73** [microsoft/vsts-team-calendar#284]
We updated the AzureDevOps2019 to version 1.1 and now we cannot see any days off in the calendar any more.
Also new added days off are not shown.
we are using Version 0.5.209 of Team Calendar (newest available)

**Comment by ruturaj-h** [comment]
Confirm that you have selected the right team at the top. Right click on page, select inspect and then refresh the page, if any errors are shown in console please paste them here. Meanwhile I will try to reproduce the issue here.

**Comment by ruturaj-h** [comment]
The version should have been different for you, seems like you have outdated copy. Go to Extension management page, "Browse local extensions", "Manage extensions" and then remove Team Calendar from there. Then go back to Extension management page, go to marketplace this time, look for team calendar, you should be able to see version 2.x.x, install that. Your data should not be affected.

**Comment by Checker73** [comment]
Hi,

 

thanks for the help.

It works now fine

 

Regards

Christian

 
 

Gesendet: Mittwoch, 15. Januar 2020 um 22:20 Uhr
Von: "ruturaj-h" <notifications@github.com>
An: microsoft/vsts-team-calendar <vsts-team-calendar@noreply.github.com>
Cc: Checker73 <chris.hecker@web.de>, Author <author@noreply.github.com>
Betreff: Re: [microsoft/vsts-team-calendar] After Update to AzureDevOps2019_1.1 (premises) days off are not any more shown up in the calendar (#284)


The version should have been different for you, seems like you have outdated copy. Go to Extension management page, "Browse local extensions", "Manage extensions" and then remove Team Calendar from there. Then go back to Extension management page, go to marketplace this time, look for team calendar, you should be able to see version 2.x.x, install that. Your data should not be affected.
