### ISSUE TITLE
Issues with add/edit since EOY?

### ISSUE THREAD

**Issue by The-Everett** [microsoft/vsts-team-calendar#286]
TFS 2017.3.1.  Anyone else having issues since EOY?  Calendar will display correctly, but add / edit now displays error message "team-calendar by ms-devlabs failed to load".  However, delete still works...must be something in the dialog.  Tried rebooting server, disable/re-enable, uninstall/re-install, no change.  Can repro issue on Chrome, Edge, and Firefox - on multiple TFS servers, version 2.0.15.  Possibly an issue with the date controls...?

**Comment by etaylor-mmm** [comment]
More to it...the error message is always displayed, but I CAN add an entry if I click from one control to another in the dialog box...the focus change event will enable the OK button.  For edit, the OK button is already enabled and does not require this focus change event.  After clicking OK on a new entry, the dialog closes, but no refresh occurs.  The Refresh button at the top of the calendar does nothing, but clicking Today or refreshing the entire page will update the calendar and show the new entry as expected.  Editing an entry will refresh on close.  Any validation failures in the dialog box (e.g. end date before start date) require clicking another control AGAIN to fire the focus change event and re-enable the OK button.

**Comment by etaylor-mmm** [comment]
Just realized that my crude workaround only works for Events, and the Category and Description controls are totally missing on the dialog, so any new entries are created as Uncategorized.  Days Off entries are not added, but previously existing Days Off entries still display on calendar.  MAJOR issue.

**Comment by ruturaj-h** [comment]
Let's continue the discussion here, please right click on the webpage, select inspect, a console will show, refresh the web page and let me know if and what error messeage you get.

**Comment by The-Everett** [comment]
Here's the log.  Looks like it's failing since I have X-Frame-Options set to sameorigin?
[dev-1579295007847.log](https://github.com/microsoft/vsts-team-calendar/files/4079194/dev-1579295007847.log)

**Comment by The-Everett** [comment]
Looks like it's failing since I have X-Frame-Options set to sameorigin?

/tfs/TestCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-calendar/Data/Scopes/User/Me/Collections/%24settings/Documents/selected-team-daec7125-83d2-4118-8c8f-c2e4e4d0638c:1 Failed to load resource: the server responded with a status of 404 (Not Found)
calendar.html:1 Refused to display 'https://server/tfs/_apis/public/gallery/publisher/ms-devlabs/extension/team-calendar/2.0.16/assetbyname/static/freeFormControls.html' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
jquery.js:5221 Blocked autofocusing on a form control in a cross-origin subframe.
(anonymous) @ jquery.js:5221
domManip @ jquery.js:5414
append @ jquery.js:5218
EditEventDialog._renderContent @ main.js:6217
(anonymous) @ main.js:6118
l @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
when @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
u.promiseDispatch @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27
t @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:27

**Comment by The-Everett** [comment]
Is there something wrong with using X-Frame-Options as sameorigin?

**Comment by The-Everett** [comment]
@ruturaj-h What do you think?

**Comment by ruturaj-h** [comment]
I think so, try disabling it and check if extension loads, are you having problems with any other extension?

**Comment by The-Everett** [comment]
@ruturaj-h I will try it, thanks.  No issues have been reported with any other extensions.

**Comment by The-Everett** [comment]
@ruturaj-h I disabled X-Frame-Options in IIS, but TFS 2017.3.1 actually adds that response header with sameorigin on its own.  No change, same error.  It could be one of the TFS hotfix patches that I applied, I'll have to try and find the exact date when I applied those.  This issue started right after the beginning of this year, so I was immediately suspect of some sort of bad date handling logic.  Must not be that since many more people would have reported the issue.  There were no extension updates between the time that the issue was reported and the first update in January was pushed out...so any recent extension updates would not have broken it.   Have there been any issues before around the extension and X-Frame-Options?  Let me know how I could troubleshoot further...I will check my patch install dates.

**Comment by The-Everett** [comment]
@ruturaj-h I found it.  TFS 2017.3.1 Patch 8.  They finally fixed the cross site scripting site and added their own X-Frame-Options in certain locations, but not the entire TFS web site...so I didn't see it.  We had added the header across the entire IIS server way before I applied the patch in December.  I removed the server wide response header, appears to be working.  Verifying with the teams now.  Just to be 100%...how to you remove an event?  I'm not seeing an obvious way to do this.  I did go change the days off, and those changes are reflected correctly from both the calendar and the sprint options.

**Comment by ruturaj-h** [comment]
Glad to hear that you were able to resolve the issue.

**Comment by The-Everett** [comment]
@ruturaj-h After correcting the X-Frame-Options, it appeared to be working.  Almost.  It appears that the Days Off entries work, but the Events have a glitch.  The control autofocus on the frame when you add an entry is throwing an cross site blocked error.  I also see a strange behavior where you add an Event, but you cannot immediately go back and edit.  Same thing, cross site blocked.  If you try to edit any Events that were already existing, that works.  But when you add, you cannot go back to the Event and edit or delete it until you click the Refresh button at the top of the calendar (or refresh the entire page).  When you add Days Off, it does not do this, and works as expected.  Something different in the way that Events are implemented vs. Days Off?

Details:

Blocked autofocusing on a form control in a cross-origin subframe.
(anonymous) @ jquery.js:5221
domManip @ jquery.js:5414
append @ jquery.js:5218
EditEventDialog._renderContent @ main.js:6217
(anonymous) @ main.js:6111
n._wrapCallback @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
setTimeout (async)
n._resolve @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
resolve @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
t.onMessage @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
n._handleMessageReceived @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
postMessage (async)
XDMChannel._sendRpcMessage @ VM107 VSS.SDK.js:395
XDMChannel._success @ VM107 VSS.SDK.js:391
(anonymous) @ VM107 VSS.SDK.js:267
XdmDeferred._wrapCallback @ VM107 VSS.SDK.js:63
(anonymous) @ VM107 VSS.SDK.js:38
(anonymous) @ VM107 VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VM107 VSS.SDK.js:91
XdmDeferred.resolve @ VM107 VSS.SDK.js:19
XdmDeferred._wrapCallback @ VM107 VSS.SDK.js:80
(anonymous) @ VM107 VSS.SDK.js:38
(anonymous) @ VM107 VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VM107 VSS.SDK.js:91
XdmDeferred.resolve @ VM107 VSS.SDK.js:19
XDMChannel.onMessage @ VM107 VSS.SDK.js:337
XDMChannelManager._handleMessageReceived @ VM107 VSS.SDK.js:637
(anonymous) @ VM107 VSS.SDK.js:656
postMessage (async)
t._sendRpcMessage @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
t._success @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
(anonymous) @ Content?bundle=vss-bundle-ext-core-vmRBvZ4VpkIyISgvnm0ZKfOsvMHEgML6x8fgxF73yR50=:57
XdmDeferred._wrapCallback @ VSS.SDK.js:63
(anonymous) @ VSS.SDK.js:38
(anonymous) @ VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VSS.SDK.js:91
XdmDeferred.resolve @ VSS.SDK.js:19
XDMChannel.onMessage @ VSS.SDK.js:337
XDMChannelManager._handleMessageReceived @ VSS.SDK.js:637
(anonymous) @ VSS.SDK.js:656
postMessage (async)
t._sendRpcMessage @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
t._success @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
n._wrapCallback @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
setTimeout (async)
n._resolve @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
resolve @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
t.onMessage @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
n._handleMessageReceived @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
postMessage (async)
XDMChannel._sendRpcMessage @ VSS.SDK.js:395
XDMChannel._success @ VSS.SDK.js:391
(anonymous) @ VSS.SDK.js:267
XdmDeferred._wrapCallback @ VSS.SDK.js:63
(anonymous) @ VSS.SDK.js:38
(anonymous) @ VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VSS.SDK.js:91
XdmDeferred.resolve @ VSS.SDK.js:19
(anonymous) @ VSS.SDK.js:74
XdmDeferred._wrapCallback @ VSS.SDK.js:63
(anonymous) @ VSS.SDK.js:38
(anonymous) @ VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VSS.SDK.js:91
XdmDeferred.resolve @ VSS.SDK.js:19
XdmDeferred._wrapCallback @ VSS.SDK.js:80
(anonymous) @ VSS.SDK.js:38
(anonymous) @ VSS.SDK.js:93
setTimeout (async)
XdmDeferred._resolve @ VSS.SDK.js:91
XdmDeferred.resolve @ VSS.SDK.js:19
XDMChannel.onMessage @ VSS.SDK.js:337
XDMChannelManager._handleMessageReceived @ VSS.SDK.js:637
(anonymous) @ VSS.SDK.js:656
postMessage (async)
t._sendRpcMessage @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
t._success @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:57
c @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:30
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:30
u.promiseDispatch @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:30
(anonymous) @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:30
t @ Content?bundle=vss-bundle-common-vqujFmNv8coYlpm1gLRjfTqaQJiC4GRYaIxkf4ZRnAUo=:30

**Comment by The-Everett** [comment]
@ruturaj-h Please advise...
