### ISSUE TITLE
AAD groups not being parsed when added to the Team

### ISSUE THREAD

**Issue by bthomas46** [microsoft/vsts-team-calendar#287]
When I add an AAD group to a team I cannot see those users when I want to add a day off entry for a user. I can only assign to users that have been assigned directly to the team.

**Comment by ruturaj-h** [comment]
Hi, work Rest client doesn't support users added a group alias. So even if I show users the actual call to create the day off would fail.

**Comment by ruturaj-h** [comment]
Duplicate of #250

**Comment by ruturaj-h** [comment]
Duplicate of #158
