### ISSUE TITLE
Uninstall/reinstall extension and data preservation

### ISSUE THREAD

**Issue by The-Everett** [microsoft/vsts-team-calendar#289]
Question:  If I uninstall the extension, then reinstall, will the existing calendar data be lost?

**Comment by ruturaj-h** [comment]
Extension data is preserved on uninstalling an extension, so there won't be any data loss on uninstall and reinstall.

**Comment by The-Everett** [comment]
Great, thank you, going to try this to resolve issue #286

**Comment by ruturaj-h** [comment]
I was about to reply to it. Let me know if reinstallation fixes it.

**Comment by The-Everett** [comment]
will do

**Comment by The-Everett** [comment]
Uninstall/reinstall does not fix the issue.  Are logs that I could provide?

**Comment by ruturaj-h** [comment]
Closing this, let's continue the conversation in #286
