### ISSUE TITLE
Team is defaulting to Root team

### ISSUE THREAD

**Issue by Stefanbnilsson** [microsoft/vsts-team-calendar#290]
When i enter the calader it will always select the "root" Team in our teamproject and not the team that was selected in the last selected view

Calander version : 2.0.15
Azure Devops Server: 2019.1.1

**Comment by ruturaj-h** [comment]
Thank you for reporting. I will try to reproduce it on my end. Haven't tested on 2019.1.1 yet.

**Comment by ruturaj-h** [comment]
#291 Fix is here and is published, please allow 24 hours to reflect changes on onprem version.
