### ISSUE TITLE
Share days-off between multiple teams

### ISSUE THREAD

**Issue by FrankVDL-Trivec** [microsoft/vsts-team-calendar#293]
In our organisation, members can/are part of multiple teams.
I like the team-calendar a lot, but controlling days-off is a bit tricky.

Would it be possible that when a day-off is added in one teams-calendar, this is automaticly been added to all other teams-calendars where this person is member of ?

**Comment by ruturaj-h** [comment]
Hi, sorry the capacity data for each team is stored seperatly. Currently there is no way to get all teams a member belongs to.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
