### ISSUE TITLE
Some things that would be great to have:

### ISSUE THREAD

**Issue by leocarva** [microsoft/vsts-team-calendar#294]
- Set the team member to an event like we do on day off
- Choose a color for each team member or category
- When I click on a category, filter only the events associated to that category.

**Comment by PedroC88** [comment]
The choosing of colors and filters are very important for shared calendars. We have a calendar shared between operations, devs and qa and it's currently not possible to see one team's tasks alone (in my use case it needs to be a shared calendar, each team might also have their own calendars).

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension but adding these suggestions to the list of ideas to consider. We'll create new issues for the enhancements.
