### ISSUE TITLE
Events Inheritance

### ISSUE THREAD

**Issue by JanMrt** [microsoft/vsts-team-calendar#295]
Is there any combination of area paths / teams / iteration paths that allows an event to show up on two distinct calenders when created? We have an organizational structure with a hierarchical distinction between Areas Paths: one comprehensive at the top, which inherits all backlog items from the teams below. I would like to implement the same logic for Events. Thanks for the good work & keep it up!

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
