### ISSUE TITLE
Unable to Read Days off on Calendar - Text is White

### ISSUE THREAD

**Issue by grubster8** [microsoft/vsts-team-calendar#296]
When team members enter days off, you cannot read it on the calendar as the text is White and the Background color is so light, it's almost invisible.  

The work around is to change DevOps to Dark Mode theme, but not everyone uses Dark Mode. 

![image](https://user-images.githubusercontent.com/57105969/74884911-eb0d9a80-5339-11ea-91a2-9d1d1949aea7.png)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
