### ISSUE TITLE
Multiple People with Days off on the Same Date overlap on the Calendar

### ISSUE THREAD

**Issue by grubster8** [microsoft/vsts-team-calendar#297]
If two or more users are off on the Same day, the text sits on top of each other, so you can't actually read it!

![image](https://user-images.githubusercontent.com/57105969/74884857-cdd8cc00-5339-11ea-88f3-b36a1a496a92.png)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
