### ISSUE TITLE
How to show the tasks based on their start and finish date times?

### ISSUE THREAD

**Issue by joymon** [microsoft/vsts-team-calendar#301]
The requirement is as follows. 

- We create work items mainly tasks with a start date and finish date including time.
- Is there any way to show those similar to how the outlook shows the meetings?
- A week's view and daily view are much appreciated.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
