### ISSUE TITLE
Request for new feature - Re-Occurring Meetings

### ISSUE THREAD

**Issue by grubster8** [microsoft/vsts-team-calendar#302]
It would be great if we can have a re-occurring items to put on the calendar.  For example, this is great to show certain sprint events that happen the same time every week\every other week.  Then we don't have to keep re-keying them in and maintaining this all the time.

**Comment by JGPease** [comment]
We would also be very interested in this feature for our organization/team. It is time-consuming to have to add recurring events/days off manually.
