### ISSUE TITLE
Making Monday as first day of the week and Sunday last

### ISSUE THREAD

**Issue by Timaz88** [microsoft/vsts-team-calendar#303]
Hello team,

As SCRUM Master I would like Calendar to show Monday as first day of week and Sunday last, so that our teams which are located at different parts of the world are not confused and aligned.

**Comment by PedroC88** [comment]
I'd also love this. I already changed all my calendars in Windows and Outlook to start on Monday, so it's a bit weird to have this one different

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
