### ISSUE TITLE
[Question] - Is there an API so we can automate adding an event to the calendar?

### ISSUE THREAD

**Issue by dazinator** [microsoft/vsts-team-calendar#305]
I'd like to extend our release pipeline for production and staging releases, to add an event to the calendar. Is there any kind of API I can use to do this?

**Comment by goldserg** [comment]
+1
I'd like to add days off from company planing vacation system

**Comment by stuartellis** [comment]
I've written notes on how to access Team Calendar from the API here:

https://www.stuartellis.name/articles/ado-team-calendar/

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
