### ISSUE TITLE
Calendar is showing a generic Icon for days off. What is it supposed to be showing?

### ISSUE THREAD

**Issue by patdelaney** [microsoft/vsts-team-calendar#306]
I just added the calendar extension and it appears to be missing an image, but not sure what is trying to show.   See screenshot
![image](https://user-images.githubusercontent.com/8147459/84298249-6dea7900-ab14-11ea-8ed7-3a172c71e6f1.png)

Any thoughts?

**Comment by patdelaney** [comment]
After some digging around, we discovered the issue, but I'm not sure we can fix it on our side, because of a "compliance" finding. The FQDN is required in the binding or it’s a compliance finding, we can’t even use the *example.com wildcard cert anymore. 

The images have url  (short name)

http://xxx-tfsapp-t01:8080/tfs/XXX%20Example%20Solutions/_api/_common/identityImage?id=c646beed-6e33-4dec-8502-68056fecbf71
if you drop that into the browser, you get an error

Bad Request - Invalid Hostname
________________________________________
HTTP Error 400. The request hostname is invalid.

You must have a context path set wrong some where
http://xxx-tfsapp-t01.corp.xxx.com:8080/ - works
http://xxx-tfsapp-t01:8080/ - does not work

Is there a setting outside of the adjusting the bindings that will populate a full FQDN for the image ID?

**Comment by jessehouwing** [comment]
This is likely caused by a misconfiguration of the public URL of the tfs/ads installation.
https://docs.microsoft.com/en-us/azure/devops/server/admin/open-admin-console?WT.mc_id=DOP-MVP-5001511&view=azure-devops-2020#view-or-change-the-public-url

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
