### ISSUE TITLE
Moving from on-prem to services we lost all our calendar data

### ISSUE THREAD

**Issue by tegaaa** [microsoft/vsts-team-calendar#309]
Is there a way to get this back my client would really like to be able to view past calendar entries.

Thanks,
ET

**Comment by jespersh** [comment]
@tegaaa what way did the migration happen? I ask because I am curious what path to take in the future myself

**Comment by jensbruggeman** [comment]
What is the status of this issue? When will this issue be solved? Any ideas?

**Comment by tegaaa** [comment]
Yes all good I have a powershell script that I will share.  you can close the issue.
