### ISSUE TITLE
Calendar not showing because content blocked

### ISSUE THREAD

**Issue by davidfilipemestre** [microsoft/vsts-team-calendar#31]
When acessing the Calendar I'm getting two CSS errors, making impossible to show the Calendar.

The errors are:
- /tfs/_static/tfs/Dev14.M95.3/_scripts/TFS/min/corejs?v=IiKWXrylMIeJdHBpXJwuE0SpVjVnmci79kLQuyG8-s41:346 Mixed Content: The page at 'https://.../tfs/_apis/public/gallery/publisher/ms-devlabs/extension/team-calendar/0.3.1/assetbyname/calendar.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://...:8080/tfs/_static/tfs/Dev14.M95.3/App_Themes/Default/VSS.Controls.css'. This request has been blocked; the content must be served over HTTPS. n._insertLinkNode @   /tfs/_static/tfs/Dev14.M95.3/_scripts/TFS/min/corejs?v=IiKWXrylMIeJdHBpXJwuE0SpVjVnmci79kLQuyG8-s41:346
- Uncaught Could not find http://...:8080/tfs/_static/tfs/Dev14.M95.3/App_Themes/Default/VSS.Controls.css or it was empty

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/18193530/14436569/3e7d5f2e-0015-11e6-9e66-03710cf530a6.png)

**Comment by hajohns** [comment]
Thank you for reporting this,
Could you help me look into this further by replying to hajohns@microsoft.com with the name of the server on which you're experiencing the errors?  

Thank you.

**Comment by davidfilipemestre** [comment]
Thank you for the quick response. E-mail sent!

Thanks in advance,
David

**Comment by insanitysauce** [comment]
We have encountered similar issues with on-premises TFS, which we worked around by inserting an "X-Forwarded-Proto: https" header on the load-balancer (Big IP F5s, in our case).
