### ISSUE TITLE
How to add a category to get them in the dropdown while creating the event in calendar 

### ISSUE THREAD

**Issue by fyreblaze11** [microsoft/vsts-team-calendar#313]
How to add a category to get them in the dropdown while creating the event in calendar

**Comment by coke** [comment]
This appears to work in the current version. I was able to add an event, type in a new category, e.g. "newcategory" for that event, select "use "newcategory" from the dropdown, and the event was created with the new category, which then appeared in the dropdown for future events.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
