### ISSUE TITLE
Calendar not showing in browser

### ISSUE THREAD

**Issue by bthomas46** [microsoft/vsts-team-calendar#315]
This is not working for one user of a team project other users can open the calendar just fine. We have tried multiple browsers and in private browsers. The calendar just spins like it is loading but never loads.

**Comment by th-zf** [comment]
Have a look at  https://github.com/microsoft/vsts-team-calendar/issues/323

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
