### ISSUE TITLE
Users are able to add dayoff entries but cannot delete the entries.

### ISSUE THREAD

**Issue by yjaibabu** [microsoft/vsts-team-calendar#321]
What permission governs the dayoff entries or events adding/deleting?

I see the users are able to dayoff entries and they couldn't delete their day off?

Please note the users are part of Azure DevOps Services Contributors group.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
