### ISSUE TITLE
Extension broken on Azure DevOps 2020

### ISSUE THREAD

**Issue by japj** [microsoft/vsts-team-calendar#330]
Hello,

It seems this extension is broken on Azure DevOps 2020. 

It gives a "_apis/WebPlatformAuth/SessionToken" 500 error.
and a promise exception with "Error issuing session token: HostAuthorizationNotFound".

**Comment by ravindrasinghshah** [comment]
I am also facing similar issue.

Request API URL: {...}/_apis/WebPlatformAuth/SessionToken
Error Response:
{"$id":"1","innerException":null,"message":"Error issuing session token: HostAuthorizationNotFound","typeName":"Microsoft.VisualStudio.Services.WebPlatform.SessionTokenException, Microsoft.VisualStudio.Services.WebApi","typeKey":"SessionTokenException","errorCode":0,"eventId":3000}

**Comment by ravindrasinghshah** [comment]
I updated Team-Calendar extension and then re-installed in required collections. That fixed this issue.
In Azure DevOps Server 2020 - Calendar is moved under 'Boards'.

**Comment by ravindrasinghshah** [comment]
> Hello,
> 
> It seems this extension is broken on Azure DevOps 2020.
> 
> It gives a "_apis/WebPlatformAuth/SessionToken" 500 error.
> and a promise exception with "Error issuing session token: HostAuthorizationNotFound".

I updated Team-Calendar extension and then re-installed in required collections. That fixed this issue.
In Azure DevOps Server 2020 - Calendar is moved under 'Boards'.

**Comment by japj** [comment]
can confirm the issue is indeed fixed
