### ISSUE TITLE
Calendar Entries disappear

### ISSUE THREAD

**Issue by jgartner78** [microsoft/vsts-team-calendar#332]
Calendar entries added to the following week disappear.  If I hit next 3x and prev 3x, there are then duplicate items showing next week.   If I hit refresh they disappear again. 

![Weird Process to get duplicates to show](https://user-images.githubusercontent.com/66317388/106154638-d04cc400-614d-11eb-9683-cff2ecea274a.JPG)
![First Load and refresh](https://user-images.githubusercontent.com/66317388/106154642-d0e55a80-614d-11eb-807f-6522c1b052c0.JPG)

**Comment by wesmacdonald** [comment]
We are experiencing the same issue, when using *Next* to navigate from January to February some events do *not* display.  If I navigate to March by pressing *Next* and then click *Prev* to navigate back to February the missing events display properly.

**Comment by Prakash2010** [comment]
I am also experiencing the same issue

**Comment by czerald** [comment]
My team at work is also experiencing this. In our case, we had to click Next then Previous for the added entries to appear.

**Comment by bravozulu1** [comment]
Yes, I can add entires and they appear to be created.  When I refresh the page, they disappear.   It's been happening for the last week.

**Comment by Lotski10** [comment]
I have encountered perhaps the same issue. I can only add and save new items until Jan 31, 2021. However starting Feb 01 onwards, whenever I add new items the entries disappear when I go to other tabs.

**Comment by runderworld** [comment]
Yeah this is a big issue affecting extension reliability. As of right now, my work team is contemplating migrating off the extension due to this unreliability.  this is _critical_ for your software get right.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
