### ISSUE TITLE
The schedule(like events and holidays) registered in February 2021 is not loaded at the first display.

### ISSUE THREAD

**Issue by Prakash2010** [microsoft/vsts-team-calendar#333]
The schedule(like events and holidays) registered in February 2021 is not loaded at the first display.
If you press "Next" and return with "Previous", the schedule registered in February will be displayed.
The days off are getting loaded without any issues.

Can you fix this bug at the earliest..

**Comment by yctdb792** [comment]
I'm sorry. I can't fix it because I don't know how to use Git

　master branch
　　src / TimeLib.ts
　　　Between lines 51 and 52

I found that adding the following line to the problem disappeared.
`current.setDate (1);`

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
