### ISSUE TITLE
Is there anyway to show Events on a Dashboard?

### ISSUE THREAD

**Issue by dkelchne** [microsoft/vsts-team-calendar#340]
Is there anyway to show Events on a Dashboard?  It would be nice to see team member days off as well as any other dates on the Team calendar

**Comment by MOlausson** [comment]
Hi @dkelchne, there's no such feature. We're triaging future work so will add this as a candidate.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
