### ISSUE TITLE
Current Date not visible in Dark Mode

### ISSUE THREAD

**Issue by VandalsBLJ** [microsoft/vsts-team-calendar#349]
The Current date is not visible in Dark Mode see attached image
![Example](https://user-images.githubusercontent.com/9883868/118654628-c27f8500-b7b6-11eb-9694-49ddf98d270f.png)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
