### ISSUE TITLE
Indirect ADO team members allowed edit rights to Team Calendar plugin

### ISSUE THREAD

**Issue by MustangMan19** [microsoft/vsts-team-calendar#350]
Members of our team would like users who have access to specific ADO teams via indirect AD security groups to show on the ADO calendar as well as be able to add time off for themselves. The users have read access when assigned indirectly to a team but are only able to add entries once removed from the AD group and are directly assigned to the team. At current this is breaks our IAM policy for best practices.  Is there a reason indirect members are not allowed to edit the calendar and can we adjust settings on our environment to allow them too?

**Comment by Warzinski** [comment]
I second this.  Team members can still set days off through the capacity tab for sprint planning, but that requires people to know what iteration their day off is in.  If their days off span multiple iterations, they also have to schedule their days off via multiple iterations.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
