### ISSUE TITLE
Add times/hours to event options

### ISSUE THREAD

**Issue by LBBrowning** [microsoft/vsts-team-calendar#351]
I want to be able to add a specific time to an event. All day is not helpful for my scheduling. It is also a problem that I can't reorder the events, they always alphabetize. Times would be the preferred sort- All day at the top and then cascading down.

**Comment by JGPease** [comment]
This option would be extremely helpful for our organization/team. We would like to migrate from our Sharepoint calendar to this one but need the ability to add specific hours.

**Comment by MOlausson** [comment]
We are triaging new work so will put this into consideration.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
