### ISSUE TITLE
How do I invoke VSTS-team-Calendar data through the REST API interface（如何通过REST API接口调用VSTS-team-Calendar数据）

### ISSUE THREAD

**Issue by 1871495799** [microsoft/vsts-team-calendar#354]
I need the data in vsts-team-calendar for secondary development（我需要vsts-team-calendar中的数据用于二次开发）

**Comment by MOlausson** [comment]
@1871495799, there's no api for this but will look into how we can give access to the data in a controlled way.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.

**Comment by 1871495799** [comment]
收到 ，谢谢

**Comment by MOlausson** [comment]
Hi @1871495799 , my Chinese is not top-notch but translate says "received, ok". Feel free to comment in English.
