### ISSUE TITLE
User cannot access the calendar

### ISSUE THREAD

**Issue by blakebaumgartner** [microsoft/vsts-team-calendar#358]
I have a user who does not see the calendar when she goes into ADO. She cannot select a team or view anything. I have tried multiple things (removing/readding her, changing license, removing/readding her from the team and project) and none of those seemed to work. I did add her to another project and she was able to see the calendar on that project. Has anyone experienced this?  [
![image](https://user-images.githubusercontent.com/66378184/136202239-ef322af7-4d3d-42f1-b9fd-efb822488e5e.png)
]

**Comment by asaccomando** [comment]
Did you ever get a response to this?

**Comment by blakebaumgartner** [comment]
Never did

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
