### ISSUE TITLE
Team Calendar is taking long than expected

### ISSUE THREAD

**Issue by cdianeg** [Microsoft/vsts-team-calendar#359]
We are using an onpremise Azure DevOps 2019 Server and the Team Calendar extension. We got this error when loading/accessing Team Calendar: "Team Calendar is taking long than expected". What could be the cause of this?

**Comment by cdianeg** [comment]
Team Calendar is now able to load on our end but we want to avoid the same issue next time, so I would like to follow up on my question above, what could be the cause of the team calendar to take time to load? What are the possible causes?

**Comment by afernandez-pc** [comment]
We are having the same problem. No clue about the root cause. Can someone help on this? Thank you.
