### ISSUE TITLE
Made event vanish

### ISSUE THREAD

**Issue by sgysel** [Microsoft/vsts-team-calendar#36]
Made events vanish when refreshing the calendar.

**Comment by hajohns** [comment]
@sgysel Could you provide more context for the issue? Is it events, days off, or both? All events, or just some? Thank you.

**Comment by sgysel** [comment]
It is only about events, but all events.
Days off are ok.
I can set an event and see it in the calendar, but as soon as I refresh the calendar, the event has gone and is no more visible.

**Comment by sgysel** [comment]
Works now fine again - thank you very much!
