### ISSUE TITLE
Calendar intermittency to add and show events

### ISSUE THREAD

**Issue by RodolfoSF** [microsoft/vsts-team-calendar#361]
I'm dealing with some problems when I try to add a new event to our team calendar at Azure. We never got this problem until 2 weeks ago and since there we are having a kind of intermittency, sometimes it works, but other not. Could you help me?

![e10d1551-58b5-4016-99f0-0c93c66238e6](https://user-images.githubusercontent.com/95436658/144471412-4ac12414-f1b0-4e0c-8115-3f6de9d36ee6.jpg)

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
