### ISSUE TITLE
Graphical Icons of the team member broken/destroyed

### ISSUE THREAD

**Issue by agile-fan** [microsoft/vsts-team-calendar#362]
s. attach
- issue is given in different browser (Edge, Chrome,...)
- refresh of browser cache was not the solution

<img width="345" alt="Calendar_Issue" src="https://user-images.githubusercontent.com/76202798/145957460-5265a67c-d376-47e9-b09e-71bd9a8292e4.PNG">

**Comment by TonyNaren1** [comment]
Hi, we've been having this issue on our ADO instance too since Dec 2022 - any fix?

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
