### ISSUE TITLE
Adding individual off days in the team calendar is not working - only possible to add days off for the hole team

### ISSUE THREAD

**Issue by thoreyjons** [microsoft/vsts-team-calendar#373]
Adding individual off days in the team calendar is not working anymore - only  possible to add days off for the hole team. 

It is still possible to add days of for each individual through the capacity of each sprint.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
