### ISSUE TITLE
Teams Calendar dropdown empty for specific user due to possible deleted team

### ISSUE THREAD

**Issue by jerryarrv** [microsoft/vsts-team-calendar#374]
We have created multiple teams in ADO.  However, some teams have been deleted as well.  Due to the error below, it's suspected that there may be an orphan reference or record tied to a specific user.  We don't have this issue for other users.  We have tried deleting the user in ADO and re-creating.  The user is a project admin so it should not be a permissions issue.  The debug info below was grabbed from a web browsing session in chrome:

"$id": "1",
    "innerException": null,
    "message": "The team with id 'cbd1909d-bf0a-430d-9662-09c6411135d9' does not exist, or you do not have permission to access it.",
    "typeName": "Microsoft.TeamFoundation.Core.WebApi.TeamNotFoundException, Microsoft.TeamFoundation.Core.WebApi",
    "typeKey": "TeamNotFoundException",
    "errorCode": 0,
    "eventId": 3000

Uncaught (in promise) TFS.WebApi.Exception: The team with id 'cbd1909d-bf0a-430d-9662-09c6411135d9' does not exist, or you do not have permission to access it.
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:24025)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22573
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22678)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:21424)

**Comment by jerryarrv** [comment]
I'm including a screenshot of the experience for the specific user:
![image](https://user-images.githubusercontent.com/105233767/177592071-3a584b49-d5b5-4b93-9a55-08208d88166f.png)

**Comment by skitch21** [comment]
We are having the same problem. Some users are unable to use the "Select Team" dropdown to choose a Team calendar.  Deleting the user from AAD and re inviting them to Azure DevOps did fix the issue for us but this isn't a viable solution for all Users. Is there a fix planned for this issue?

**Comment by lovelysandwich** [comment]
Just had precisely this issue happen.  A team was deleted and now the calendar doesn't show any of the other teams in the drop down.

```
Uncaught (in promise) TFS.WebApi.Exception: The team with id '51666c78-7070-4307-9f3a-a4b2a2346b7b' does not exist, or you do not have permission to access it.
    at Object.<anonymous> (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:24025)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22573
    at Object.next (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:22678)
    at a (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/team-calendar/2.0.16/1579110530797/dist/Calendar.js:94:21424)
```
Is there a way we can fix this for ourselves?

**Comment by jamesbr-ashn** [comment]
### Workaround to Select Team drop down does not display list:

1. Open your browser to https://dev.azure.com/{organization}/_apis/projects/{projectName}/teams/ to get a list of teams in json format.
2. Get the id value of any team in the list. This will be a GUID.
3. Open the browser to https://dev.azure.com/{organization}/{projectName}/_apps/hub/ms-devlabs.team-calendar.team-calendar?team={teamId}

When the browser opens to this team, it will be captured as the new selectedTeamId and you should not have any problems going forward.

**Comment by jerryarrv** [comment]
> 3. Open the browser to [https://dev.azure.com/{organization}/{projectName}/_apps/hub/ms-devlabs.team-calendar.team-calendar?team={teamId}](https://dev.azure.com/%7Borganization%7D/%7BprojectName%7D/_apps/hub/ms-devlabs.team-calendar.team-calendar?team=%7BteamId%7D)
> 
> When the browser opens to this team, it will be captured as the new selectedTeamId and you should not have any problems going forward.

I greatly appreciate your workaround!  We've tested this on a user with the issue, and it works.  Our previous attempt to solve this with another user a few months ago was having to re-create their AD account.  It was pretty painful.  This was a much simpler solution over the bug in MS Teams Calendar.

**Comment by jerryarrv** [comment]
I'm marking this as Closed with the workaround.  I do feel the dev team should still address the root issue.
