### ISSUE TITLE
Azure DevOps calendar can't disable weekends days

### ISSUE THREAD

**Issue by alexis19apl** [microsoft/vsts-team-calendar#377]
Our team make use of this calendar to schedule the days off we plan, but the visual is really confusing with the weekends visualized it make an overlap that makes harder and confusing the schedules time frame.
The request is to unselect or disable the days "weekends, Sunday, Saturday" that aren't relevant for our teams"

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
