### ISSUE TITLE
Add daysOff via api

### ISSUE THREAD

**Issue by marinmurgic45** [microsoft/vsts-team-calendar#380]
Hi, will it be possible to add days off via API calls?
Thanks!

**Comment by MOlausson** [comment]
Hi @marinmurgic45, we're triaging work and will look into how we can support extension/integration/automation scenarios. But currently we don't provide an api for this.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
