### ISSUE TITLE
Capacity of current sprint ereased by day-off

### ISSUE THREAD

**Issue by fabianschlier** [Microsoft/vsts-team-calendar#39]
When adding a new day off for a sprint which has already capacities assigned, the capacity for the team member is set to zero. Additionally the _activity_ setting is deleted.

Recreate:
* Go to capacity screen and add capacities (e.g. by copying from last sprint) for sprint X
* See _activity_ and _capacity_ fields filled for team member A
* Go to calendar view
* Add a day off for team member A within the sprint X
* Go to capacity screen of sprint X
* See that _activity_ and _capacity_ values are gone

Installation details:
* TFS 2015 Update 1 on premise
* Team Calendar 0.3.3

**Comment by hajohns** [comment]
Thank you for reporting, this should be fixed now. Please let us know if you are still seeing issues.
