### ISSUE TITLE
Can not access Team calendar in Azure

### ISSUE THREAD

**Issue by mrtroybaker2598** [microsoft/vsts-team-calendar#400]
I am unable to get into the team calendar. Attached are 2 images. An error and a screenshot of the calendar page. 

![ee35d50b-46e5-43c6-b18f-d423fd4efa08](https://user-images.githubusercontent.com/119608290/205084155-0a80424e-d2f1-4d71-8652-7d4fcc38bdfd.jpg)
![e7f43392-8bc4-4a49-a207-074702d5ed5f](https://user-images.githubusercontent.com/119608290/205084229-5f8ab72d-04c9-4e06-b2c8-095b19ad4925.jpg)

**Comment by mericstam** [comment]
Hi thanks for reporting, the team will take a look

**Comment by pabrams** [comment]
I was unable to reproduce on https://github.com/microsoft/vsts-team-calendar/commit/ce3f1c4961447bc19684c194f1148ccdb3a1d143

**Comment by jamesbwilkinson** [comment]
We have a similar issue. Team member is unable to view the calendar as teams list is not populated at all. They are a member of several teams. We have tried removing the user from the org and re-adding them with no effect. We see an error relating to "the team with id xxx does not exist or you do not have permission to access it" The team referenced does not exist. We have extension version 2.0.22.

**Comment by pabrams** [comment]
Hmm, you could try referencing a team that exists... maybe that would work.

**Comment by jamesbwilkinson** [comment]
@pabrams, as described by @UweStein there is no option to select or change a team, the menu is empty. Perhaps there is a default team set somewhere against the user but I don't see it anywhere. Does the extension store or reference such information?
