### ISSUE TITLE
Events are not saved

### ISSUE THREAD

**Issue by RaymondHartog** [microsoft/vsts-team-calendar#438]
When add an event it looks like it's saved, but after browser refresh event isn't available any more. 

See screenshots:
![image](https://user-images.githubusercontent.com/21220490/217512857-6efa37ba-0b12-49dd-9571-4f63e8bce5eb.png)
 After browser refresh:
![image](https://user-images.githubusercontent.com/21220490/217513003-26852a7b-a1cf-4b9f-97eb-e7cf90824602.png)

**Comment by DevFlake** [comment]
Same problem here!

**Comment by juedo8** [comment]
We also have this BUG! pls fixed it quickly!

**Comment by michael-buchner** [comment]
When will this bug be fixed?

**Comment by AminTi** [comment]
Hi! can you  please test it again and let me know if you still have the same issues

**Comment by michael-buchner** [comment]
Seems to be fixed now, thanks a lot!

**Comment by MOlausson** [comment]
All, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by MOlausson** [comment]
Thanks for verifying, closing as resolved.
