### ISSUE TITLE
Two Microsoft DevLab Team Calendar versions published in the Marketplace

### ISSUE THREAD

**Issue by RaymondHartog** [microsoft/vsts-team-calendar#439]
Version 2.0.1

![image](https://user-images.githubusercontent.com/21220490/217514027-88cf554e-869a-48fa-8b4b-5ed61b7aa31f.png)

<br>

**Left Team Calendar Extension:**

<br>

![image](https://user-images.githubusercontent.com/21220490/217515182-be9c309b-2c76-4a98-8bb9-44f21cf491b0.png)

<br>

**Right Team Calendar Extension:**

<br>

![image](https://user-images.githubusercontent.com/21220490/217514925-1b14443a-9711-4765-8ad8-4966490f1297.png)

**Comment by AminTi** [comment]
Thanks for reporting.
