### ISSUE TITLE
Azure DevOps Calendar not visible

### ISSUE THREAD

**Issue by UrsulaConley** [microsoft/vsts-team-calendar#441]
I have the calendar plugin for Azure DevOps.  I am an Admin in the instance/on the project.  I am unable to use the calendar function in one of our project while others on my team are.  I am able to access other projects.  Just not this one.  Photo attached.

![IT Ticket - ADO Calendar](https://user-images.githubusercontent.com/93405963/219717866-2b246da2-5124-46e1-a44e-530677fa035e.JPG)

**Comment by AminTi** [comment]
Thanks for reporting, can you describe your environment? Can you see any error in the console or network logs in the browser (using F12, debug tools)?

**Comment by MangliB** [comment]
Calendar renders the same as the screenshot in my environment.  I'm running Azure DevOps Server 2019, extension version 2.0.17.

Console shows getQueryParams is not a function 
![image](https://user-images.githubusercontent.com/126520469/221686904-98693da9-0a8a-43cf-9d4d-8f3003b289a2.png)

**Comment by MOlausson** [comment]
@UrsulaConley @MangliB , we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by MangliB** [comment]
@MOlausson  Calendar is working again with 2.0.22

**Comment by MOlausson** [comment]
Perfect, thanks for confirming @MangliB! Closing this as resolved.
