### ISSUE TITLE
Lost access to all calendar entries after latest update 2.0.17

### ISSUE THREAD

**Issue by JJKW1984** [microsoft/vsts-team-calendar#443]
We have reports in our organization that the calendar links have stopped working.
I've noticed that the GUIDs have change on some links.
When teams select calendar from the board menu all the data is missing from the calendars.

**Comment by Mortos98** [comment]
I have found that if you substitute a team name for the team id that works as a reasonable work around, though its been temperamental at times

**Comment by jonghyunee** [comment]
Our company also uses DevOps On-premise, and the calendar does not work after being forced to update to version 2.0.17. The previous version is the version installed on May 9, 2020. There is definitely a problem, so please fix it.

**Comment by woodshop2300** [comment]
Another DevOps On-premise users here, I see the same thing as the others.. I could conceivably grab the old version off a backup server, but even if that works i have the feeling it would just auto update to this version again.

**Comment by AminTi** [comment]
Thanks for reporting, We are working on it, We will release an update as soon as possible.

**Comment by MOlausson** [comment]
All, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by JJKW1984** [comment]
We are still seeing blank calendars. Was there any possibility of data loss?

**Comment by MOlausson** [comment]
@JJKW1984 what version of ADO are you on? Also can you verify that the extension has been updated to the latest version?

**Comment by JJKW1984** [comment]
We are on ado sevices.It update this morning 7am estsent from my mobile deviceOn Mar 6, 2023, at 2:51 PM, Mathias Olausson ***@***.***> wrote:﻿
@JJKW1984 what version of ADO are you on? Also can you verify that the extension has been updated to the latest version?

**Comment by MOlausson** [comment]
@JJKW1984 can you share an update? Are you still having problems or have you been able to work around and move forward?

**Comment by JJKW1984** [comment]
@MOlausson Things are back to normal and all data is present.
