### ISSUE TITLE
TFS Calendar will not load

### ISSUE THREAD

**Issue by Dan-DCYF** [microsoft/vsts-team-calendar#444]
Late yesterday afternoon, we lost our ability to view the TFS Project calendars.   It was working until about 2:30 p.m.
This is the screen I get when I attempt to click on the calendar: 
 
![2023-02-23_17-09-29](https://user-images.githubusercontent.com/126213899/221069447-eafd8898-bc90-45b6-95f4-e03c8db1544e.png)
![2023-02-23_17-09-29](https://user-images.githubusercontent.com/126213899/221069548-7d2ddc88-f0e0-4718-bbfb-3d38e26fc8c7.png)

**Comment by AminTi** [comment]
Thanks for reporting, We are working on it, We will release an update as soon as possible.

**Comment by Dan-DCYF** [comment]
Thank you so much for looking into this. Will we need to download a new extension?

**Comment by AminTi** [comment]
Hi, Try now and let me know if you still have the same problem.

**Comment by MOlausson** [comment]
@Dan-DCYF, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by Dan-DCYF** [comment]
Pruthvi,

Can you check the version to be sure that we have 2.0.22? Also, does it matter that I am using 2017? My calendar is still not working.

Thank you,

Dan Gebhart

**Comment by Dan-DCYF** [comment]
Good Morning,

I just tried it again and I am getting the same error:
***@***.***


Thank you,
Dan Gebhart | Project Manager
Information Technology | MERIT, Background Check Portal & Background Check System
Cell 360-481-9008
1310 Jefferson St SE| PO Box 40991
Olympia, WA 98501
www.dcyf.wa.gov<http://www.dcyf.wa.gov/>
[2021-06-09_16-21-55-100][DCYF Logo Color]

**Comment by Dan-DCYF** [comment]
Hello Dan,

I just re-installed 2.0.22 version Team calendar extension. Looks like its working fine now. Please find the below screenshot. Let me know if you still see any issues from your end.
***@***.***

Regards,

Pruthvi Kuncham (he/him) | DevOps Engineer | C. (469) 955-9966
Information Technology Division
[DCYF_Logo]<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.dcyf.wa.gov%2F&data=05%7C01%7Ckuncham.pruthvi%40dcyf.wa.gov%7C4628aea037e6454e5e2108da70a7c0ee%7C11d0e217264e400a8ba057dcc127d72d%7C0%7C0%7C637946163189430470%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YJvQ34gy%2BVpYkcWB6OX6QbNe7fZXOqO8yrSEbNLHpd4%3D&reserved=0>

From: Gebhart, Dan (DCYF) ***@***.***>
Sent: Monday, March 6, 2023 6:07 AM
To: Pruthvi, Kuncham (DCYF) ***@***.***>
Cc: Mention ***@***.***>; microsoft/vsts-team-calendar ***@***.***>; microsoft/vsts-team-calendar ***@***.***>
Subject: RE: [microsoft/vsts-team-calendar] TFS Calendar will not load (Issue #444)

Pruthvi,

Can you check the version to be sure that we have 2.0.22? Also, does it matter that I am using 2017? My calendar is still not working.

Thank you,

Dan Gebhart

**Comment by Dan-DCYF** [comment]
Good Afternoon,

We rolled back the Extension to the older version and the TFS Calendar is now working! Thank you so much for your quick turn-around for this issue.

Dan Gebhart

From: Gebhart, Dan (DCYF)
Sent: Monday, March 6, 2023 6:34 AM
To: microsoft/vsts-team-calendar ***@***.***>; microsoft/vsts-team-calendar ***@***.***>
Cc: Author ***@***.***>; Pruthvi, Kuncham (DCYF) ***@***.***>
Subject: RE: [microsoft/vsts-team-calendar] TFS Calendar will not load (Issue #444)

Good Morning,

I just tried it again and I am getting the same error:
***@***.***


Thank you,
Dan Gebhart | Project Manager
Information Technology | MERIT, Background Check Portal & Background Check System
Cell 360-481-9008
1310 Jefferson St SE| PO Box 40991
Olympia, WA 98501
www.dcyf.wa.gov<http://www.dcyf.wa.gov/>
[2021-06-09_16-21-55-100][DCYF Logo Color]

**Comment by Dan-DCYF** [comment]
Good Afternoon,

The Roll back to version 2.0.22 resolved the issue and the TFS Calendar now displays as expected!!!

Thank you so much!


Dan Gebhart | Project Manager
Information Technology | MERIT, Background Check Portal & Background Check System
Cell 360-481-9008
1310 Jefferson St SE| PO Box 40991
Olympia, WA 98501
www.dcyf.wa.gov<http://www.dcyf.wa.gov/>
[2021-06-09_16-21-55-100][DCYF Logo Color]

Dan

From: Gebhart, Dan (DCYF)
Sent: Monday, March 6, 2023 6:07 AM
To: Pruthvi, Kuncham (DCYF) ***@***.***>
Cc: Mention ***@***.***>; microsoft/vsts-team-calendar ***@***.***>; microsoft/vsts-team-calendar ***@***.***>
Subject: RE: [microsoft/vsts-team-calendar] TFS Calendar will not load (Issue #444)

Pruthvi,

Can you check the version to be sure that we have 2.0.22? Also, does it matter that I am using 2017? My calendar is still not working.

Thank you,

Dan Gebhart

**Comment by MOlausson** [comment]
@Dan-DCYF, great to hear it's working for you!
