### ISSUE TITLE
The extension has stopped working on TFS version 16 since the latest update

### ISSUE THREAD

**Issue by robertmaddprog** [microsoft/vsts-team-calendar#445]
Team Calendar by Microsoft DevLabs failed to load.

**Comment by DavidVerroPMIC** [comment]
Bump

**Comment by RedNeckRedCoat** [comment]
Has stopped working for TFS 2018 as well

**Comment by raygarcia-01** [comment]
TFS18 here, not working either. Please revert change or help correct. There are no traces available we can provide other than "Team Calendar by Microsoft DevLabs failed to load"

**Comment by AminTi** [comment]
Hi! we are working on it.

**Comment by MOlausson** [comment]
All, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by robertmaddprog** [comment]
^ It's still not working. Do we have to uninstall and reinstall?

**Comment by MOlausson** [comment]
Please do, we tried that and for us it's loading as expected. Which Azure DevOps/TFS version are you running?

**Comment by robertmaddprog** [comment]
If I uninstall, will I lose existing entries in the calendar?

Microsoft Visual Studio Team Foundation Server
Version 16.131.28601.4

**Comment by DavidVerroPMIC** [comment]
The uninstall/reinstall did not work for us unfortunately.  Thank you for continuing to work on this.

**Comment by raygarcia-01** [comment]
For testing purposes I installed it fresh in a new collection. After seeing it's working fine I went to check the previous impacted collection. To my (good) surprise the calendar function was also corrected in the other collections. I'm on TFS2018.

**Comment by MOlausson** [comment]
Thanks @raygarcia-01 for confirming. Closing the issue based on this confirmation.
