### ISSUE TITLE
Azure DevOps Calendar is missing data - users need to move back and forth a month in order to see all data on calendar

### ISSUE THREAD

**Issue by mandarin77** [microsoft/vsts-team-calendar#449]

**Comment by AminTi** [comment]
No description provided.

**Comment by mandarin77** [comment]
My apologies. Azure DevOps Calendar is missing data - users need to move back and forth a month in order to see all data on calendar. For example, when the calendar is opened, it shows some data, but not all. When the user clicks back a month and then back to the original month viewed, then all of the calendar events appear.

**Comment by AminTi** [comment]
Thanks for reporting,  we are woking on it.

**Comment by mandarin77** [comment]
You're welcome. Please let me know if you need any further information.

**Comment by mandarin77** [comment]
Good afternoon. Please advise if there is any update on this issue and if you need any additional information.

**Comment by M288112** [comment]
Similar issue discovered today with the DevOps Calendar.  We have several entries on 12/26 for holiday time off and only 7 are fully visible.  The 8th and beyond are not visible and no means to scroll either the calendar as a whole or the daily details.  Are scroll bars configurable by the calendar Admin perhaps?
