### ISSUE TITLE
Team Calendar extension stopped working after update to 2.0.17

### ISSUE THREAD

**Issue by cdianeg** [microsoft/vsts-team-calendar#453]
Hi, MS DevLabs Team.

We are using heavily using the Team Calendar extension for our Azure DevOps Server 2019/TFS 2019 and I noticed that after the update 2.0.17 was pushed, it has stopped working. Now, I see another update was pushed yesterday (update 2.0.18) but that didn't fix the issue. Can someone check this please because we have a team that is dependent on the Team Calendar extension and their work has been affected by this.

Our TFS version is Version Dev17.M153.2

**Comment by AminTi** [comment]
Thanks for reporting, We are working on it, can please test it again and let me know if you still have the same issues

**Comment by MOlausson** [comment]
@cdianeg, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by cdianeg** [comment]
It is working now. Thank you
