### ISSUE TITLE
Roll-back the latest version of Team Calendar to 0.5.210, or set the entire 0.5.210 version code to a version number higher than 2.0.19 and release it. please.

### ISSUE THREAD

**Issue by jonghyunee** [microsoft/vsts-team-calendar#454]
Please roll-back the latest version of Team Calendar to 0.5.210, or set the entire 0.5.210 version code to a version number higher than 2.0.19 and release it. please. All of our schedule data is not available, and we are unable to record additional schedules. If you don't solve this problem quickly, you will have to use another calendar because there will be a huge setback to the company's work. please solve it please! Please roll-back the latest version of Team Calendar to 0.5.210, or set the entire 0.5.210 version code to a version number higher than 2.0.19 and release it. please.

**Comment by AminTi** [comment]
Thanks for reporting, We are working on it,  can please test it again and let me know if you still have the same issues

**Comment by MOlausson** [comment]
@jonghyunee, we decided to revert the latest change to resolve the issue it caused for Azure DevOps 2018 and 2019. Can you check that the Calendar look ok for you again with the 2.0.22 version?

**Comment by jonghyunee** [comment]
hanks for the quick fix response. Automatically updated to version 2.0.21 but unfortunately doesn't work. There are setbacks in the company's work, but I'll wait for them to be fixed.
![image](https://user-images.githubusercontent.com/72309265/223284996-13b56c22-8dc6-4df9-b766-21fbc62606f6.png)

**Comment by jonghyunee** [comment]
@AminTi @MOlausson 

Below is a screenshot of the version of our DevOps On-Premise software and the Team Calendar version.

![image](https://user-images.githubusercontent.com/72309265/223286663-c2d5d099-d57b-4be6-8005-c09f921fe100.png)

![image](https://user-images.githubusercontent.com/72309265/223286609-129830ed-d98d-409b-a517-8cb68bbc73bc.png)

**Comment by jonghyunee** [comment]
@AminTi @MOlausson 
Since version 2.0.22 it's working very well. Thanks for fixing the bug.
