### ISSUE TITLE
All custom events dissapeared

### ISSUE THREAD

**Issue by afernandez-pc** [microsoft/vsts-team-calendar#455]
Hi, all our custom events has suddenly disappeared from the calendar, everything worked fine yesterday but seems like the latest release contains a bug. Could you please fix or revert the latest release?

**Comment by MOlausson** [comment]
@afernandez-pc , can you share which version of the extension you have (2.0.22?) and which Azure DevOps version you are on?

**Comment by MOlausson** [comment]
Thanks. We are collecting feedback, so far no new issue reported on 2020. Is this the same as #442.

**Comment by alexnwood** [comment]
@MOlausson There might be a different issue more severe than #442 where the events reappear after navigation. Our events are missing and never reappear even after navigating. We're on 2.0.22.

**Comment by alexnwood** [comment]
Note: newly created events show up as expected. The dozens of events created prior to today are nowhere to be found...

**Comment by fmuecke** [comment]
Same here: all our planned dates are gone since _Monday_ (v 2.0.21).  Newly crated dates will show up.

Please fix or revert. v2.0.22 is no improvement so far. Maybe the error exists since 2.0.18 - this I can't tell.

![image](https://user-images.githubusercontent.com/7921024/224292712-aa03767e-08ee-4e47-98f5-0a6f948a40cb.png)

**Comment by grubster8** [comment]
Are there any updates on this?  If we don't have this resolved, I think we have to abandon using this extension and come up with a new tool, thanks!

**Comment by vishnu3133** [comment]
@MOlausson  We have the same issue. lost all the custom events.
Team Calendar is updated to version 2.0.22
Version - Azure DevOps Server 2020 Update 1.1

Note: newly created events show up as expected. The dozens of events created prior to today are nowhere to be found...

**Comment by MOlausson** [comment]
We are still investigating this issue. Would anyone be able to confirm if events created prior to Feb 23 are shown?

**Comment by Frothe1035** [comment]
No, not even events created prior to Feb 23, they're all gone. :(
Only newly-created ones are shown now.

**Comment by vishnu3133** [comment]
> We are still investigating this issue. Would anyone be able to confirm if events created prior to Feb 23 are shown?

No, not showing any events created prior to 9th of March, only showing the one created after 9th of March.

**Comment by melance** [comment]
We don't see any events at all regardless of date and if we try to add new events, we get a security popup that we can't get past.

**Comment by AminTi** [comment]
We regret to inform you that we could not recover the data you reported. If you have any questions, please feel free to contact us, and we will do our best to assist you.
