### ISSUE TITLE
Calendar lost all the entries

### ISSUE THREAD

**Issue by vishnu3133** [microsoft/vsts-team-calendar#457]
Team Calendar is updated to version 2.0.22 and we lost our data. Calendar is blank.
Version - Azure DevOps Server 2020 Update 1.1

**Comment by MOlausson** [comment]
@vishnu3133 can you share how you've upgraded your environment? Can you see any old events if you select events in the past?

**Comment by vishnu3133** [comment]
I haven't upgraded by myself, but the extension history shows it is upgraded to 2.0.22. I cannot see any old events in the calendar.  I cannot see any options to select the old events.
![image](https://user-images.githubusercontent.com/86986957/224674181-75df4e49-6285-4d10-aab5-2d84c42cbc19.png)

**Comment by AminTi** [comment]
We regret to inform you could not recover the data you reported. If you have any questions, please feel free to contact us, and we will do our best to assist you.
