### ISSUE TITLE
Not able to build

### ISSUE THREAD

**Issue by TapanKumarBarik** [microsoft/vsts-team-calendar#485]
I have cloned the code and run the necessary cmd , when i am runnign npm run build 

i am getting the below issue 

Could not find a required file.
  Name: index.html
  Searched in: C:\vsts-team-calendar\public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vsts-teams-calendar@2.0.0 build: `react-scripts build`

**Comment by AminTi** [comment]
Please review the package.json scripts as there is no 'npm run build' included. If you wish to execute 'npm run build,' you'll need to make some adjustments.  try npm run build:dev  or  npm run build:release

**Comment by TapanKumarBarik** [comment]
![image](https://github.com/microsoft/vsts-team-calendar/assets/55124761/e751b305-b555-4f0d-bbe0-6b63d6aabbc4)
@AminTi

**Comment by TapanKumarBarik** [comment]
Hi @AminTi  ,

appreciate your response

**Comment by AminTi** [comment]
Let's schedule an appointment for next week, so I can assist you.

**Comment by AminTi** [comment]
Let me know if you still need some assistance.

**Comment by TapanKumarBarik** [comment]
Hi @AminTi  , Sorry you could have mentioned :P Yes, I am able to build an extension now Thank you so much. Sorry I missed to respond you
