### ISSUE TITLE
One Days Off update per user and update propogated to all teams of which user is a member.

### ISSUE THREAD

**Issue by JessMol** [microsoft/vsts-team-calendar#498]
One Days Off update per user and update propogated to all teams of which user is a member within a project.
Similar to need in Multiple teams in the same project - Calendar should rollup #167.  (This issue was noted as an enhancement in Sept. 21, 2017)

**Comment by AminTi** [comment]
Hi, we are currently working on a different extension for the team calendar. We will prioritize bug fixes for the moment

**Comment by JessMol** [comment]
It doesn't sound like the same enhancement.  #167 is suggesting a master calender.  I am suggesting make one change and all the user's team calenders can be updated with that change.

**Comment by AminTi** [comment]
HI, I  have been working on other extensions and will prioritize this issue as soon as possible.

**Comment by JessMol** [comment]
I received an email stating this issue will be prioritized as soon as possible, but this item is showing as still closed.  Will it be reopened?
