### ISSUE TITLE
Need To Integrate Azure DevOps Board calendar with my outlook

### ISSUE THREAD

**Issue by ajnaidu-pinc** [microsoft/vsts-team-calendar#516]
Good morning!
Hi Team,

I would like to integrate Azure DevOps Board calendar with my outlook to get alerts.
Can you suggest or extend some help please.

**Comment by AminTi** [comment]
Hi, Thank you for reaching out. Unfortunately, we currently do not have the possibility to assist with integrating Azure DevOps Board with Outlook.
