### ISSUE TITLE
Need to Export the data from the Team Calendar Extension

### ISSUE THREAD

**Issue by swissrerakeshv** [microsoft/vsts-team-calendar#520]
Hi Team,

We want to export the data from the Team Calendar extension and as we checked there is no direct options to export the data ,so could you please help us is there any other way is available to export the data from the team calendar extension.

Regards,
Rakesh

**Comment by AminTi** [comment]
Hi, Unfortunately, there isn't an option to export data please feel free to reach out if you have any other questions or concerns.
