### ISSUE TITLE
How to change months in drop down option?

### ISSUE THREAD

**Issue by ehoang07** [microsoft/vsts-team-calendar#524]
Is there a setting to update the months shown in the drop down? We're in November, but it starts from August. 
And is there possibility to list more than 6 months?

![Image](https://github.com/user-attachments/assets/72498ba0-d727-4207-8998-f9e2c49d7de1)

**Comment by AminTi** [comment]
Hi, we have been working on the team calendar to improve the on-prem version. We will release it as soon as possible, and I will also try to resolve this issue in the same release

**Comment by ehoang07** [comment]
> Hi, we have been working on the team calendar to improve the on-prem version. We will release it as soon as possible, and I will also try to resolve this issue in the same release
