### ISSUE TITLE
Adding event results in 403 forbidden

### ISSUE THREAD

**Issue by JustRonald** [microsoft/vsts-team-calendar#54]
As TFS administrator I installed the Team Calender extensions but it results in a 403 error with the ExtensionDataCollectionQuery (_https://mytfsserver/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-calendar/ExtensionDataCollectionQuery_) and Documents (_https://mytfsserver/tfs/DefaultCollection/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/team-calendar/Data/Scopes/Default/Current/Collections/bc6e8cdb-f1dd-4452-a225-765186bcc069/Documents_) requests for the project users. As admin I am able to successfully create events. I cannot find any permissions settings for this extension, am I missing something?

**Comment by hajohns** [comment]
Could send a Fiddler capture of this scenario to hajohns@microsoft.com? Thank you.
