### ISSUE TITLE
Calendar by Microsoft DevLabs failed to load.Learn More about this extension, including available support options.

### ISSUE THREAD

**Issue by ghost** [microsoft/vsts-team-calendar#55]
Working before  May 3. Any ideas?

I got following error:
Calendar by Microsoft DevLabs failed to load.Learn More about this extension, including available support options.

When i go to Team Services instance.

**Comment by raclede** [comment]
I think this might be related to ZScaler blocking the assets.. Can someone provide which url /address should i request to get unblocked?

**Comment by sumo300** [comment]
Here are the errors I get with on-prem TFS 2015 Update 2 when I try to Add an item:

    Sandbox access violation: Blocked a frame at "https://[url]" from accessing a frame at "null".  Both frames are sandboxed and lack the "allow-same-origin" flag.
    Uncaught SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'.

**Comment by hajohns** [comment]
@sumo300 - Thank you for reporting, this is a known issue and we are working on a solution. 

@raclede - Could you email me at hajohns@microsoft.com with a Fiddler trace or any network errors you see trying to load the calendar? Thank you.
