### ISSUE TITLE
New Profile Image is not reflected in Calendar events

### ISSUE THREAD

**Issue by ShirleyWilliamson** [Microsoft/vsts-team-calendar#60]
Update Profile Picture
View Calendar entry for that person
Expected : New profile image replaces existing image
Actual : old image is still displayed

**Comment by hajohns** [comment]
I believe that's a result of the old image being cached for a length of time (I think 12 hours). Do you see the new picture if you clear the browser cache and refresh?

**Comment by ShirleyWilliamson** [comment]
Cleared the cache, refreshed, closed and reopened browser - still seeing old image

**Comment by willsmythe** [comment]
Added this to the list of known issues in the overview.md - https://github.com/Microsoft/vsts-team-calendar/blob/master/overview.md
