### ISSUE TITLE
Import external calendars (ICS)

### ISSUE THREAD

**Issue by papadi** [microsoft/vsts-team-calendar#61]
It would be great if we can import calendars from external locations. This way we could include feeds with local bank holidays, leaves or team meetings.

**Comment by hajohns** [comment]
That would be great! Team Calendar doesn't (yet) support importing other ICS formatted calendars, however it does support contributed event sources. 
To see external events in your Team Calendar, you can create a new event source as an extension, such as in this example: https://github.com/Microsoft/vsts-extension-samples/tree/master/calendar-public-events

Thank you!
