### ISSUE TITLE
Expose the calendar in .ics format so that mail programs such as Outlook can open it.

### ISSUE THREAD

**Issue by askaliate** [microsoft/vsts-team-calendar#64]
Hi,

Is there a plan to allow some integration with internet calendar functionality so this can be opened by mail programs - it would be super useful to just see this info in Outlook not necessarily make changes.

**Comment by ckoeber** [comment]
Seconded, this would be a great feature.

**Comment by oliverkocsis** [comment]
Explicit +1

**Comment by josersleal** [comment]
this should have had been a top feature imo. 
Meanwhile this seems to be a way to achieve some level of sync: https://www.cloudguy.pro/sync-visual-studio-online-items-to-outlook-task-list/

**Comment by pabrams** [comment]
I implemented this without much trouble.  Wrote a node script to read the data from the database and construct .ics files.   A scheduled task calls the script, then copies the results to a generic web site so they can be linked to by users.  The hardest part was the colors, but I managed to find a way to calculate the "closest" color among the default Outlook categories, and apply that.  Now people can overlay the calendar in Outlook with other calendars, and use the Outlook views.  Works great!  Read-only.

**Comment by soumyamishra76** [comment]
Any update on the solution to this?

**Comment by pabrams** [comment]
The repository hasn't been updated in years. There are more than a couple dozen open PRs, so opening more doesn't seem fruitful.

**Comment by pabrams** [comment]
I was thinking about forking the repo and starting to maintain it, myself, but I don't really have the time right now.
