### ISSUE TITLE
HTTP Error 401.2 - Unauthorized

### ISSUE THREAD

**Issue by decvs** [microsoft/vsts-team-calendar#65]
Getting a 401.2 when starting the calendar.
The calendar is shown, but there is a Spinning control in the event column.
All request from the addin are ok, but only the requests to the iterations fail with the 401.2 error.

Request GET /tfs/XXXX/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx/_apis/work/teamsettings/iterations HTTP/1.1

 <h3>HTTP Error 401.2 - Unauthorized</h3> 
  <h4>You are not authorized to view this page due to invalid authentication headers.</h4> 
</div> 

<div class="content-container"> 
 <fieldset><h4>Most likely causes:</h4> 
  <ul>  <li>No authentication protocol (including anonymous) is selected in IIS.</li>   <li>Only integrated authentication is enabled, and a client browser was used that does not support integrated authentication.</li>  <li>Integrated authentication is enabled and the request was sent through a proxy that changed the authentication headers before they reach the Web server.</li>    <li>The Web server is not configured for anonymous access and a required authorization header was not received.</li>    <li>The "configuration/system.webServer/authorization" configuration section may be explicitly denying the user access.</li> </ul> 
 </fieldset> 
</div>

**Comment by evakili** [comment]
I have installed the extension on an on-premise server. I forced to hack the extension to load the dependencies locally: #83. You can see the hack on my fork: evakili/vsts-team-calendar@2219cf526287b6db11d6eff6ac23ea7e5539d2d8.

But I have a problem now that seems to be same as above:
Clicking on links in calendar ('Iterations' or 'Days off links') I lost my connection to TFS in some pages. No iterations listed on Iterations page, dashboard widgets does not loaded, card settings are not shown, etc.
These errors are shown in Chrome inspector:
* Uncaught SecurityError: Failed to set the 'cookie' property on 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.
* *(Many times)* Failed to load resource: the server responded with a status of 401 (Unauthorized)
