### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by ups216** [microsoft/vsts-team-calendar#66]
Installed on my account, but I cannot see anything on the hub page, just showing a blank page with disabled + button and reload button.

**Comment by willsmythe** [comment]
Can you send your *.visualstudio.com account name to vsointegration@microsoft.com so we can investigate?

**Comment by devgig** [comment]
We have TFS 2015 Update 3 and about half of the team have a Blank Screen for the Calendar.  Is there some kind of special permission or something that needs to be enabled on the Browser to see the Calendar?  We have an On Premise instance of TFS.

**Comment by evakili** [comment]
We've the same problem on our TFS 2015. The server is not connected to the Internet, so some third party libraries (e.g jQuery) could not be loaded. In the extension these libraries are loaded from CDNs.
