### ISSUE TITLE
Calendar showing wrong date versus the right side.

### ISSUE THREAD

**Issue by AlexNajem** [microsoft/vsts-team-calendar#68]
When adding a vacation, the calendar shows the icon on the right date, but on the right hand side it shows the wrong date.

![image](https://cloud.githubusercontent.com/assets/19717439/16128943/b71a70b8-33d0-11e6-91c5-134a1d40ebc5.png)

**Comment by CraigHead** [comment]
Happening here too.

**Comment by pjslak** [comment]
Found the same issue TFS2015 SP3 Installed

**Comment by DanCarpenterLM** [comment]
This issue is also happening with iterations being off
![2017-03-23_10-36-22](https://cloud.githubusercontent.com/assets/26628564/24253231/1b9cd9e2-0fb6-11e7-869d-839076fe4a45.png)
