### ISSUE TITLE
Region-independent 'first day of week' setting

### ISSUE THREAD

**Issue by mbronk** [microsoft/vsts-team-calendar#72]
The first day of week seems to be set based on client's language setting which is obviously a very good default, but becomes a little problematic when your primary Accept-Language does not match the culture you're in (happens often when testing/changing the browser etc.)

**Proposal:** As an alternative, you could allow to configure a fixed first day of week setting (e.g. per-project).
This would work to the most effect, when combined with a feature to allow to choose 'working days' (ideally - get the selection from capacity tab's settings) and, say, gray them out

_Real-world example: I recently found out my team's velocity was not calculated properly, because some team members were adding their vacations on Sundays/non-working-days (b/c on a different client machines it was always 'the leftmost box' :) )_

**Comment by JesperTreetop** [comment]
Agreed; As a Swedish programmer using English versions of everything, I had no idea this was even taken into consideration at all. I thought it was a missing option.

**Comment by weird-dreams** [comment]
All our developers in germany use the english version of VSTS because dev things sound terrible in german.
But nonetheless will our calendars start on monday as first day of week!

**Comment by weird-dreams** [comment]
Please add an option for this !!!

**Comment by weird-dreams** [comment]
Our company is located in Germany. Every developer uses VSTS with english regional settings.
But when regarding dates in an calendar the week begins with MONDAY.
PLEASE ADD AN OPTION TO SET THE FIRST DAY OF THE WEEK... 
TIA, Andi

**Comment by AlexeyBuzdin** [comment]
Linking similar issues to this one
https://github.com/microsoft/vsts-team-calendar/issues/236
https://github.com/microsoft/vsts-team-calendar/issues/115
