### ISSUE TITLE
All previous used categories do not show up in category dropdown list

### ISSUE THREAD

**Issue by doenges** [microsoft/vsts-team-calendar#74]
I created new events in June & July all with categories.  Categories showed up in the categories dropdown list when I was adding the events.  Then I created new events for August and there are no categories in the categories dropdown list.

**Comment by hajohns** [comment]
The category dropdown list should be populated only by categories for existing events in the current view frame. Were there already events created in August when you started creating new events?

**Comment by doenges** [comment]
No.

So you are saying that by design I have to recreate my events when they have been used previously in a prior view frame?  They should be persistent.



­­___________
Dan Doenges
952-240-0967

**Comment by SiskaM** [comment]
I agree. If you ever entered a category in a team calendar, it should be available in the following months as well. Otherwise what good are they?
