### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by corrededos** [microsoft/vsts-team-calendar#76]
**First of all, thanks for an awsome extension!**

I would like to suggest the possibility to create recurring events such as birthdays, dailys etc.
NB! I don't know how to tag this issue as an enhancement.

Cheers!
/Mike

**Comment by trevorsg** [comment]
Just fyi, you can extend the Calendar by providing your own event source, in case you are interested in building this feature :) There is an example of a contributed event source [here](https://github.com/Microsoft/vsts-extension-samples/tree/master/calendar-public-events).

**Comment by corrededos** [comment]
Thanks! 
I guessed that contributing would be possible since it's the whole idea of open source (GitHub).
But It has been years since I coded som I am a bit afraid that I will ruin something. ;) 
I might look in to it once I built up some courage, It would actually be fun to build!

Cheers Trevor!
