### ISSUE TITLE
Calendar Add event UX issues

### ISSUE THREAD

**Issue by ranganathg** [microsoft/vsts-team-calendar#78]
![image](https://cloud.githubusercontent.com/assets/4153129/17322839/28e7bfe6-58bd-11e6-8792-5d7af5971ebb.png)

The description textarea is not properly aligned when the the Add Event dialog is expanded from the bottom right. 
Also once expanded, the description text area doesnt expand correctly showing all the corners. 
Also, mouse hover on the description text area doesnt show a arrowed handle.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
