### ISSUE TITLE
Cannot create event for one day only

### ISSUE THREAD

**Issue by iamkarlson** [Microsoft/vsts-team-calendar#8]
Cannot create one day event.
1. Creating event
![screenshot_0213](https://cloud.githubusercontent.com/assets/4534374/9754890/473b6e16-56de-11e5-8220-56460601d06d.png)
2. Event created with incorrect sum
![screenshot_0214](https://cloud.githubusercontent.com/assets/4534374/9754895/4d80ed5a-56de-11e5-83de-686b7499a122.png)
3. Change date from datepicker (datepicker format date in incorrect format)
![screenshot_0215](https://cloud.githubusercontent.com/assets/4534374/9754908/68396c08-56de-11e5-929e-d374f580d60a.png)
4. Same result
![screenshot_0214](https://cloud.githubusercontent.com/assets/4534374/9754926/8ecd3728-56de-11e5-9e5f-f31d8b5430d1.png)
5. Create for two days
![screenshot_0216](https://cloud.githubusercontent.com/assets/4534374/9754959/e7eff5c0-56de-11e5-8fa5-e436802e4745.png)
6. Unexpected behavior
![screenshot_0217](https://cloud.githubusercontent.com/assets/4534374/9754971/08093416-56df-11e5-92f8-da55f7478542.png)
7.  Start date greater than end date
![screenshot_0218](https://cloud.githubusercontent.com/assets/4534374/9754982/2017013c-56df-11e5-83da-9c6c392501f4.png)
8. Can't create
![screenshot_0219](https://cloud.githubusercontent.com/assets/4534374/9754987/294f5916-56df-11e5-825c-18c736aaee53.png)

**Comment by dmarcey** [comment]
Thanks for reporting this. Unfortunately, I'm not able to reproduce. Perhaps it is a time zone issue. Can you go here:
https://<YourAccountName>.visualstudio.com/_details/profile/preferences

and let me know what the time zone you have set in VSO is, in addition to the time zone you have set in your Operating System, so that I can set mine to the same and try to reproduce?

Thanks.

**Comment by iamkarlson** [comment]
No, I change my time zone settings to same with vso, but still same result. Can't create one day event.

**Comment by iamkarlson** [comment]
I can give you access to my calendar where you can check. drop me letter on iamkarlson@gmail.com

**Comment by Guadzilah** [comment]
You cant because under my GPL License you cant change it under law not the software owner

**Comment by iamkarlson** [comment]
@Guadzilah what are you talking about? I can't what?

**Comment by Guadzilah** [comment]
try something new

**Comment by iamkarlson** [comment]
@Guadzilah please explain what you mean.

**Comment by Guadzilah** [comment]
Can not make any changes its in the GPL license agreement thank you

**Comment by iamkarlson** [comment]
Sorry, I really don't understand about what you are talking about. I
understand that it's something covered gpl. But about which particular
thing you I don't know..

**Comment by Guadzilah** [comment]
I'm the author of Windows 8 and I don't really understand git maybe we can connect in some other fashion I need your help to get in the right zone you may not be able to change it

**Comment by thechrisjohnson** [comment]
I've blocked Guadzilah, but I'm not sure if I'm considered the "owner" of this repository to prevent future spam.

**Comment by iamkarlson** [comment]
Thanks
