### ISSUE TITLE
Adding a day off should apply to all teams (and possibly projects)

### ISSUE THREAD

**Issue by willsmythe** [microsoft/vsts-team-calendar#84]
When a user adds a "day off" via the Team Calendar, it's reasonable that the user should be marked as "off" in other teams/projects, not just the current project.

**Comment by gniederme** [comment]
At least there should be an option to do so (checkbox 'share with other calendars'). Sometimes it makes sense to add "day off" to one team calendar because the person is working for the other team during that timeframe and vise versa.
