### ISSUE TITLE
Unable to add day off

### ISSUE THREAD

**Issue by RoarG** [microsoft/vsts-team-calendar#86]
I am not able to add day off when left clicking the calendar. Events work fine
http://imgur.com/vhZjQQO

**Comment by willsmythe** [comment]
Are you seeing this problem on Team Services? Or TFS (on-prem)? If TFS, which Update are you running?

**Comment by MattTraxinger** [comment]
I was having the same issue. I was able to click the Days Off Link in the upper right hand corner of the screen to see that I didn't have any iterations assigned. Once I did that the Add Event dialog was populated. Instead of it being blank it should show an appropriate error message.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
