### ISSUE TITLE
Clicking Iterations label incorrectly opening project-level Work admin hub

### ISSUE THREAD

**Issue by willsmythe** [microsoft/vsts-team-calendar#89]
It should open the team-level hub (which was recently split out from the project-level hub).

This came from this customer review of the extension on the Marketplace:
_I have found following issues (on TFS 2015 Update 2 ): 1) if I click on "Iterations" link - I see no Iteration in admin screen, but if I go using regular links - I see all my iterations_

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
