### ISSUE TITLE
Adding Event doesn't save

### ISSUE THREAD

**Issue by Raistlen38** [microsoft/vsts-team-calendar#92]
On TFS 2015 Update 3 on-premises here. Just recently (after the upgrade to Update 3), adding an Event to the Team Calendar does not save between sessions. It will look like it's there in the calendar when you initially add it, but navigating away from the calendar and then back to it will result in it disappearing. Adding 'Days Off' works just fine though. 

Any ideas?

**Comment by dmarcey** [comment]
Are there any error messages in the browser console (F12 tools)? Feel free to reach out to me directly at demarcey AT microsoft.com and I can try to help you debug.

**Comment by Raistlen38** [comment]
Hi dmarcey,

I do get 2 errors in the Console when clicking on a day. 

SCRIPT5: Access is denied.

File: calendarServices.html, Line: 1, Column: 1
SCRIPT5: Access is denied.

File: calendar.html, Line: 1, Column: 1

Saving either an Event or a Day Off did not generate additional errors. Nor did navigating away from the calendar and then back to it (or even switching months and coming back to the original month). 

There were other informational messages that came up in the console, but they were xmlrequests that looked ok to me, but I can provide them if you think they might help.

Thanks for the very quick response!

**Comment by dmarcey** [comment]
If you could provide the error messages of the AJAX calls when creating an event, that would be helpful (or even a fiddler trace would be best), so that I can see whether or not this call is actually getting the to the TFS server. My guess is that it is not, which is why it appears that the event is there, until you refresh and then it is gone.

Thanks!

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
