### ISSUE TITLE
Color highlighting for all Sprints within the calendar 

### ISSUE THREAD

**Issue by ckoeber** [microsoft/vsts-team-calendar#95]
Currently the calendar correctly highlights the current sprint; would be great if the calendar can highlight the days for each sprint; past, present and future.

This way you can clearly see the actual timespan of the sprints within the calendar.

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
