### ISSUE TITLE
Outlook integration or export as ics

### ISSUE THREAD

**Issue by M-WOLF** [microsoft/vsts-team-calendar#99]
Outlook integration or export as ics would be great

**Comment by Stoffe** [comment]
An integration with the Outlook calendar would be super needed, I want a common calendar that can hold all information about the project, and sync with our sharepoint site as well.
Integration with Outlook is a necessary feature!

**Comment by ggondim** [comment]
Not just export but also publish the iCal for integration with another agendas (Google Calendar, etc.)

**Comment by nicksterx** [comment]
Duplicate of #64

**Comment by MOlausson** [comment]
We're closing old issues so we can get back to actively maintaining the extension. Feel free to reopen if this is still an issue for you.
